// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(KitharaFFIInternal)
import KitharaFFIInternal
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_kithara_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_kithara_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureKitharaFfiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.
// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterFloat: FfiConverterPrimitive {
    typealias FfiType = Float
    typealias SwiftType = Float

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Float {
        return try lift(readFloat(&buf))
    }

    public static func write(_ value: Float, into buf: inout [UInt8]) {
        writeFloat(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDouble: FfiConverterPrimitive {
    typealias FfiType = Double
    typealias SwiftType = Double

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Double {
        return try lift(readDouble(&buf))
    }

    public static func write(_ value: Double, into buf: inout [UInt8]) {
        writeDouble(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




/**
 * FFI-facing audio player with UUID-based queue management.
 */
public protocol AudioPlayerProtocol: AnyObject, Sendable {
    
    func defaultRate()  -> Float
    
    /**
     * Insert an item into the queue.
     *
     * If the item's resource is already loaded, it is inserted into both
     * the FFI queue and the engine immediately. If not yet loaded,
     * the item is placed in the FFI queue and an async auto-load task
     * is spawned; upon completion the resource is inserted into the engine.
     *
     * # Errors
     *
     * Returns [`FfiError::InvalidArgument`] if `after` is not in the queue.
     */
    func insert(item: AudioPlayerItem, after: AudioPlayerItem?) throws 
    
    func isMuted()  -> Bool
    
    func items()  -> [AudioPlayerItem]
    
    func pause() 
    
    func play() 
    
    func rate()  -> Float
    
    /**
     * # Errors
     *
     * Returns [`FfiError::InvalidArgument`] if the item is not in the queue.
     */
    func remove(item: AudioPlayerItem) throws 
    
    func removeAllItems() 
    
    /**
     * Seek to a position in the current item.
     *
     * The callback is invoked synchronously with `true` if the seek command
     * was accepted, `false` otherwise (matches `AVPlayer` semantics).
     */
    func seek(toSeconds: Double, callback: SeekCallback) 
    
    func setDefaultRate(rate: Float) 
    
    func setMuted(muted: Bool) 
    
    func setObserver(observer: PlayerObserver) 
    
    func setVolume(volume: Float) 
    
    /**
     * Return a snapshot of the player's current state.
     *
     * Cheap synchronous read — Swift should use this instead of caching
     * state locally.
     */
    func snapshot()  -> FfiPlayerSnapshot
    
    func volume()  -> Float
    
}
/**
 * FFI-facing audio player with UUID-based queue management.
 */
open class AudioPlayer: AudioPlayerProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_kithara_ffi_fn_clone_audioplayer(self.handle, $0) }
    }
public convenience init() {
    let handle =
        try! rustCall() {
    uniffi_kithara_ffi_fn_constructor_audioplayer_new($0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_kithara_ffi_fn_free_audioplayer(handle, $0) }
    }

    

    
open func defaultRate() -> Float  {
    return try!  FfiConverterFloat.lift(try! rustCall() {
    uniffi_kithara_ffi_fn_method_audioplayer_default_rate(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Insert an item into the queue.
     *
     * If the item's resource is already loaded, it is inserted into both
     * the FFI queue and the engine immediately. If not yet loaded,
     * the item is placed in the FFI queue and an async auto-load task
     * is spawned; upon completion the resource is inserted into the engine.
     *
     * # Errors
     *
     * Returns [`FfiError::InvalidArgument`] if `after` is not in the queue.
     */
open func insert(item: AudioPlayerItem, after: AudioPlayerItem?)throws   {try rustCallWithError(FfiConverterTypeFfiError_lift) {
    uniffi_kithara_ffi_fn_method_audioplayer_insert(
            self.uniffiCloneHandle(),
        FfiConverterTypeAudioPlayerItem_lower(item),
        FfiConverterOptionTypeAudioPlayerItem.lower(after),$0
    )
}
}
    
open func isMuted() -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_kithara_ffi_fn_method_audioplayer_is_muted(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func items() -> [AudioPlayerItem]  {
    return try!  FfiConverterSequenceTypeAudioPlayerItem.lift(try! rustCall() {
    uniffi_kithara_ffi_fn_method_audioplayer_items(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func pause()  {try! rustCall() {
    uniffi_kithara_ffi_fn_method_audioplayer_pause(
            self.uniffiCloneHandle(),$0
    )
}
}
    
open func play()  {try! rustCall() {
    uniffi_kithara_ffi_fn_method_audioplayer_play(
            self.uniffiCloneHandle(),$0
    )
}
}
    
open func rate() -> Float  {
    return try!  FfiConverterFloat.lift(try! rustCall() {
    uniffi_kithara_ffi_fn_method_audioplayer_rate(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * # Errors
     *
     * Returns [`FfiError::InvalidArgument`] if the item is not in the queue.
     */
open func remove(item: AudioPlayerItem)throws   {try rustCallWithError(FfiConverterTypeFfiError_lift) {
    uniffi_kithara_ffi_fn_method_audioplayer_remove(
            self.uniffiCloneHandle(),
        FfiConverterTypeAudioPlayerItem_lower(item),$0
    )
}
}
    
open func removeAllItems()  {try! rustCall() {
    uniffi_kithara_ffi_fn_method_audioplayer_remove_all_items(
            self.uniffiCloneHandle(),$0
    )
}
}
    
    /**
     * Seek to a position in the current item.
     *
     * The callback is invoked synchronously with `true` if the seek command
     * was accepted, `false` otherwise (matches `AVPlayer` semantics).
     */
open func seek(toSeconds: Double, callback: SeekCallback)  {try! rustCall() {
    uniffi_kithara_ffi_fn_method_audioplayer_seek(
            self.uniffiCloneHandle(),
        FfiConverterDouble.lower(toSeconds),
        FfiConverterTypeSeekCallback_lower(callback),$0
    )
}
}
    
open func setDefaultRate(rate: Float)  {try! rustCall() {
    uniffi_kithara_ffi_fn_method_audioplayer_set_default_rate(
            self.uniffiCloneHandle(),
        FfiConverterFloat.lower(rate),$0
    )
}
}
    
open func setMuted(muted: Bool)  {try! rustCall() {
    uniffi_kithara_ffi_fn_method_audioplayer_set_muted(
            self.uniffiCloneHandle(),
        FfiConverterBool.lower(muted),$0
    )
}
}
    
open func setObserver(observer: PlayerObserver)  {try! rustCall() {
    uniffi_kithara_ffi_fn_method_audioplayer_set_observer(
            self.uniffiCloneHandle(),
        FfiConverterTypePlayerObserver_lower(observer),$0
    )
}
}
    
open func setVolume(volume: Float)  {try! rustCall() {
    uniffi_kithara_ffi_fn_method_audioplayer_set_volume(
            self.uniffiCloneHandle(),
        FfiConverterFloat.lower(volume),$0
    )
}
}
    
    /**
     * Return a snapshot of the player's current state.
     *
     * Cheap synchronous read — Swift should use this instead of caching
     * state locally.
     */
open func snapshot() -> FfiPlayerSnapshot  {
    return try!  FfiConverterTypeFfiPlayerSnapshot_lift(try! rustCall() {
    uniffi_kithara_ffi_fn_method_audioplayer_snapshot(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func volume() -> Float  {
    return try!  FfiConverterFloat.lift(try! rustCall() {
    uniffi_kithara_ffi_fn_method_audioplayer_volume(
            self.uniffiCloneHandle(),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAudioPlayer: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = AudioPlayer

    public static func lift(_ handle: UInt64) throws -> AudioPlayer {
        return AudioPlayer(unsafeFromHandle: handle)
    }

    public static func lower(_ value: AudioPlayer) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AudioPlayer {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: AudioPlayer, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAudioPlayer_lift(_ handle: UInt64) throws -> AudioPlayer {
    return try FfiConverterTypeAudioPlayer.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAudioPlayer_lower(_ value: AudioPlayer) -> UInt64 {
    return FfiConverterTypeAudioPlayer.lower(value)
}






/**
 * FFI-facing audio player item with UUID identity and lazy loading.
 */
public protocol AudioPlayerItemProtocol: AnyObject, Sendable {
    
    /**
     * String representation of the item's unique ID.
     */
    func id()  -> String
    
    /**
     * Synchronous fire-and-forget load.
     *
     * Spawns resource creation on `FFI_RUNTIME`. Errors are reported
     * through [`ItemObserver::on_event`] instead of being returned.
     * Double-calls are ignored (idempotent).
     */
    func load() 
    
    func preferredPeakBitrate()  -> Double
    
    func preferredPeakBitrateForExpensiveNetworks()  -> Double
    
    func setObserver(observer: ItemObserver) 
    
    func setPreferredPeakBitrate(bitrate: Double) 
    
    func setPreferredPeakBitrateForExpensiveNetworks(bitrate: Double) 
    
    func setStoreOptions(store: StoreOptions) 
    
    func url()  -> String
    
}
/**
 * FFI-facing audio player item with UUID identity and lazy loading.
 */
open class AudioPlayerItem: AudioPlayerItemProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_kithara_ffi_fn_clone_audioplayeritem(self.handle, $0) }
    }
    /**
     * Create a new item. Does not start loading — call [`load`] explicitly.
     */
public convenience init(url: String, additionalHeaders: [String: String]?) {
    let handle =
        try! rustCall() {
    uniffi_kithara_ffi_fn_constructor_audioplayeritem_new(
        FfiConverterString.lower(url),
        FfiConverterOptionDictionaryStringString.lower(additionalHeaders),$0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_kithara_ffi_fn_free_audioplayeritem(handle, $0) }
    }

    

    
    /**
     * String representation of the item's unique ID.
     */
open func id() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_kithara_ffi_fn_method_audioplayeritem_id(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Synchronous fire-and-forget load.
     *
     * Spawns resource creation on `FFI_RUNTIME`. Errors are reported
     * through [`ItemObserver::on_event`] instead of being returned.
     * Double-calls are ignored (idempotent).
     */
open func load()  {try! rustCall() {
    uniffi_kithara_ffi_fn_method_audioplayeritem_load(
            self.uniffiCloneHandle(),$0
    )
}
}
    
open func preferredPeakBitrate() -> Double  {
    return try!  FfiConverterDouble.lift(try! rustCall() {
    uniffi_kithara_ffi_fn_method_audioplayeritem_preferred_peak_bitrate(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func preferredPeakBitrateForExpensiveNetworks() -> Double  {
    return try!  FfiConverterDouble.lift(try! rustCall() {
    uniffi_kithara_ffi_fn_method_audioplayeritem_preferred_peak_bitrate_for_expensive_networks(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func setObserver(observer: ItemObserver)  {try! rustCall() {
    uniffi_kithara_ffi_fn_method_audioplayeritem_set_observer(
            self.uniffiCloneHandle(),
        FfiConverterTypeItemObserver_lower(observer),$0
    )
}
}
    
open func setPreferredPeakBitrate(bitrate: Double)  {try! rustCall() {
    uniffi_kithara_ffi_fn_method_audioplayeritem_set_preferred_peak_bitrate(
            self.uniffiCloneHandle(),
        FfiConverterDouble.lower(bitrate),$0
    )
}
}
    
open func setPreferredPeakBitrateForExpensiveNetworks(bitrate: Double)  {try! rustCall() {
    uniffi_kithara_ffi_fn_method_audioplayeritem_set_preferred_peak_bitrate_for_expensive_networks(
            self.uniffiCloneHandle(),
        FfiConverterDouble.lower(bitrate),$0
    )
}
}
    
open func setStoreOptions(store: StoreOptions)  {try! rustCall() {
    uniffi_kithara_ffi_fn_method_audioplayeritem_set_store_options(
            self.uniffiCloneHandle(),
        FfiConverterTypeStoreOptions_lower(store),$0
    )
}
}
    
open func url() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_kithara_ffi_fn_method_audioplayeritem_url(
            self.uniffiCloneHandle(),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAudioPlayerItem: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = AudioPlayerItem

    public static func lift(_ handle: UInt64) throws -> AudioPlayerItem {
        return AudioPlayerItem(unsafeFromHandle: handle)
    }

    public static func lower(_ value: AudioPlayerItem) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AudioPlayerItem {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: AudioPlayerItem, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAudioPlayerItem_lift(_ handle: UInt64) throws -> AudioPlayerItem {
    return try FfiConverterTypeAudioPlayerItem.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAudioPlayerItem_lower(_ value: AudioPlayerItem) -> UInt64 {
    return FfiConverterTypeAudioPlayerItem.lower(value)
}






/**
 * Receives item-level state changes from Rust.
 */
public protocol ItemObserver: AnyObject, Sendable {
    
    func onEvent(event: FfiItemEvent) 
    
}
/**
 * Receives item-level state changes from Rust.
 */
open class ItemObserverImpl: ItemObserver, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_kithara_ffi_fn_clone_itemobserver(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_kithara_ffi_fn_free_itemobserver(handle, $0) }
    }

    

    
open func onEvent(event: FfiItemEvent)  {try! rustCall() {
    uniffi_kithara_ffi_fn_method_itemobserver_on_event(
            self.uniffiCloneHandle(),
        FfiConverterTypeFfiItemEvent_lower(event),$0
    )
}
}
    

    
}



// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceItemObserver {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // This creates 1-element array, since this seems to be the only way to construct a const
    // pointer that we can pass to the Rust code.
    static let vtable: [UniffiVTableCallbackInterfaceItemObserver] = [UniffiVTableCallbackInterfaceItemObserver(
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            do {
                try FfiConverterTypeItemObserver.handleMap.remove(handle: uniffiHandle)
            } catch {
                print("Uniffi callback interface ItemObserver: handle missing in uniffiFree")
            }
        },
        uniffiClone: { (uniffiHandle: UInt64) -> UInt64 in
            do {
                return try FfiConverterTypeItemObserver.handleMap.clone(handle: uniffiHandle)
            } catch {
                fatalError("Uniffi callback interface ItemObserver: handle missing in uniffiClone")
            }
        },
        onEvent: { (
            uniffiHandle: UInt64,
            event: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterTypeItemObserver.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onEvent(
                     event: try FfiConverterTypeFfiItemEvent_lift(event)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        }
    )]
}

private func uniffiCallbackInitItemObserver() {
    uniffi_kithara_ffi_fn_init_callback_vtable_itemobserver(UniffiCallbackInterfaceItemObserver.vtable)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeItemObserver: FfiConverter {
    fileprivate static let handleMap = UniffiHandleMap<ItemObserver>()

    typealias FfiType = UInt64
    typealias SwiftType = ItemObserver

    public static func lift(_ handle: UInt64) throws -> ItemObserver {
        if ((handle & 1) == 0) {
            // Rust-generated handle, construct a new class that uses the handle to implement the
            // interface
            return ItemObserverImpl(unsafeFromHandle: handle)
        } else {
            // Swift-generated handle, get the object from the handle map
            return try handleMap.remove(handle: handle)
        }
    }

    public static func lower(_ value: ItemObserver) -> UInt64 {
         if let rustImpl = value as? ItemObserverImpl {
             // Rust-implemented object.  Clone the handle and return it
            return rustImpl.uniffiCloneHandle()
         } else {
            // Swift object, generate a new vtable handle and return that.
            return handleMap.insert(obj: value)
         }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ItemObserver {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: ItemObserver, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeItemObserver_lift(_ handle: UInt64) throws -> ItemObserver {
    return try FfiConverterTypeItemObserver.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeItemObserver_lower(_ value: ItemObserver) -> UInt64 {
    return FfiConverterTypeItemObserver.lower(value)
}






/**
 * Receives player-level state changes from Rust.
 *
 * All calls happen on an arbitrary background thread.
 * Platform bindings must dispatch to the UI thread as needed.
 */
public protocol PlayerObserver: AnyObject, Sendable {
    
    func onEvent(event: FfiPlayerEvent) 
    
}
/**
 * Receives player-level state changes from Rust.
 *
 * All calls happen on an arbitrary background thread.
 * Platform bindings must dispatch to the UI thread as needed.
 */
open class PlayerObserverImpl: PlayerObserver, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_kithara_ffi_fn_clone_playerobserver(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_kithara_ffi_fn_free_playerobserver(handle, $0) }
    }

    

    
open func onEvent(event: FfiPlayerEvent)  {try! rustCall() {
    uniffi_kithara_ffi_fn_method_playerobserver_on_event(
            self.uniffiCloneHandle(),
        FfiConverterTypeFfiPlayerEvent_lower(event),$0
    )
}
}
    

    
}



// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfacePlayerObserver {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // This creates 1-element array, since this seems to be the only way to construct a const
    // pointer that we can pass to the Rust code.
    static let vtable: [UniffiVTableCallbackInterfacePlayerObserver] = [UniffiVTableCallbackInterfacePlayerObserver(
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            do {
                try FfiConverterTypePlayerObserver.handleMap.remove(handle: uniffiHandle)
            } catch {
                print("Uniffi callback interface PlayerObserver: handle missing in uniffiFree")
            }
        },
        uniffiClone: { (uniffiHandle: UInt64) -> UInt64 in
            do {
                return try FfiConverterTypePlayerObserver.handleMap.clone(handle: uniffiHandle)
            } catch {
                fatalError("Uniffi callback interface PlayerObserver: handle missing in uniffiClone")
            }
        },
        onEvent: { (
            uniffiHandle: UInt64,
            event: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterTypePlayerObserver.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onEvent(
                     event: try FfiConverterTypeFfiPlayerEvent_lift(event)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        }
    )]
}

private func uniffiCallbackInitPlayerObserver() {
    uniffi_kithara_ffi_fn_init_callback_vtable_playerobserver(UniffiCallbackInterfacePlayerObserver.vtable)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePlayerObserver: FfiConverter {
    fileprivate static let handleMap = UniffiHandleMap<PlayerObserver>()

    typealias FfiType = UInt64
    typealias SwiftType = PlayerObserver

    public static func lift(_ handle: UInt64) throws -> PlayerObserver {
        if ((handle & 1) == 0) {
            // Rust-generated handle, construct a new class that uses the handle to implement the
            // interface
            return PlayerObserverImpl(unsafeFromHandle: handle)
        } else {
            // Swift-generated handle, get the object from the handle map
            return try handleMap.remove(handle: handle)
        }
    }

    public static func lower(_ value: PlayerObserver) -> UInt64 {
         if let rustImpl = value as? PlayerObserverImpl {
             // Rust-implemented object.  Clone the handle and return it
            return rustImpl.uniffiCloneHandle()
         } else {
            // Swift object, generate a new vtable handle and return that.
            return handleMap.insert(obj: value)
         }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PlayerObserver {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: PlayerObserver, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePlayerObserver_lift(_ handle: UInt64) throws -> PlayerObserver {
    return try FfiConverterTypePlayerObserver.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePlayerObserver_lower(_ value: PlayerObserver) -> UInt64 {
    return FfiConverterTypePlayerObserver.lower(value)
}






/**
 * Callback for seek completion.
 */
public protocol SeekCallback: AnyObject, Sendable {
    
    func onComplete(finished: Bool) 
    
}
/**
 * Callback for seek completion.
 */
open class SeekCallbackImpl: SeekCallback, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_kithara_ffi_fn_clone_seekcallback(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_kithara_ffi_fn_free_seekcallback(handle, $0) }
    }

    

    
open func onComplete(finished: Bool)  {try! rustCall() {
    uniffi_kithara_ffi_fn_method_seekcallback_on_complete(
            self.uniffiCloneHandle(),
        FfiConverterBool.lower(finished),$0
    )
}
}
    

    
}



// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceSeekCallback {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // This creates 1-element array, since this seems to be the only way to construct a const
    // pointer that we can pass to the Rust code.
    static let vtable: [UniffiVTableCallbackInterfaceSeekCallback] = [UniffiVTableCallbackInterfaceSeekCallback(
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            do {
                try FfiConverterTypeSeekCallback.handleMap.remove(handle: uniffiHandle)
            } catch {
                print("Uniffi callback interface SeekCallback: handle missing in uniffiFree")
            }
        },
        uniffiClone: { (uniffiHandle: UInt64) -> UInt64 in
            do {
                return try FfiConverterTypeSeekCallback.handleMap.clone(handle: uniffiHandle)
            } catch {
                fatalError("Uniffi callback interface SeekCallback: handle missing in uniffiClone")
            }
        },
        onComplete: { (
            uniffiHandle: UInt64,
            finished: Int8,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterTypeSeekCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onComplete(
                     finished: try FfiConverterBool.lift(finished)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        }
    )]
}

private func uniffiCallbackInitSeekCallback() {
    uniffi_kithara_ffi_fn_init_callback_vtable_seekcallback(UniffiCallbackInterfaceSeekCallback.vtable)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSeekCallback: FfiConverter {
    fileprivate static let handleMap = UniffiHandleMap<SeekCallback>()

    typealias FfiType = UInt64
    typealias SwiftType = SeekCallback

    public static func lift(_ handle: UInt64) throws -> SeekCallback {
        if ((handle & 1) == 0) {
            // Rust-generated handle, construct a new class that uses the handle to implement the
            // interface
            return SeekCallbackImpl(unsafeFromHandle: handle)
        } else {
            // Swift-generated handle, get the object from the handle map
            return try handleMap.remove(handle: handle)
        }
    }

    public static func lower(_ value: SeekCallback) -> UInt64 {
         if let rustImpl = value as? SeekCallbackImpl {
             // Rust-implemented object.  Clone the handle and return it
            return rustImpl.uniffiCloneHandle()
         } else {
            // Swift object, generate a new vtable handle and return that.
            return handleMap.insert(obj: value)
         }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SeekCallback {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: SeekCallback, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSeekCallback_lift(_ handle: UInt64) throws -> SeekCallback {
    return try FfiConverterTypeSeekCallback.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSeekCallback_lower(_ value: SeekCallback) -> UInt64 {
    return FfiConverterTypeSeekCallback.lower(value)
}




/**
 * Snapshot of the player's current state, returned by [`AudioPlayer::snapshot`].
 *
 * Fields are `Option` when no current item is loaded — callers should
 * not assume defaults.
 */
public struct FfiPlayerSnapshot: Equatable, Hashable {
    public let status: FfiPlayerStatus
    public let currentTime: Double?
    public let duration: Double?
    public let rate: Float
    public let defaultRate: Float
    public let volume: Float
    public let muted: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(status: FfiPlayerStatus, currentTime: Double?, duration: Double?, rate: Float, defaultRate: Float, volume: Float, muted: Bool) {
        self.status = status
        self.currentTime = currentTime
        self.duration = duration
        self.rate = rate
        self.defaultRate = defaultRate
        self.volume = volume
        self.muted = muted
    }

    

    
}

#if compiler(>=6)
extension FfiPlayerSnapshot: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiPlayerSnapshot: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiPlayerSnapshot {
        return
            try FfiPlayerSnapshot(
                status: FfiConverterTypeFfiPlayerStatus.read(from: &buf), 
                currentTime: FfiConverterOptionDouble.read(from: &buf), 
                duration: FfiConverterOptionDouble.read(from: &buf), 
                rate: FfiConverterFloat.read(from: &buf), 
                defaultRate: FfiConverterFloat.read(from: &buf), 
                volume: FfiConverterFloat.read(from: &buf), 
                muted: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: FfiPlayerSnapshot, into buf: inout [UInt8]) {
        FfiConverterTypeFfiPlayerStatus.write(value.status, into: &buf)
        FfiConverterOptionDouble.write(value.currentTime, into: &buf)
        FfiConverterOptionDouble.write(value.duration, into: &buf)
        FfiConverterFloat.write(value.rate, into: &buf)
        FfiConverterFloat.write(value.defaultRate, into: &buf)
        FfiConverterFloat.write(value.volume, into: &buf)
        FfiConverterBool.write(value.muted, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiPlayerSnapshot_lift(_ buf: RustBuffer) throws -> FfiPlayerSnapshot {
    return try FfiConverterTypeFfiPlayerSnapshot.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiPlayerSnapshot_lower(_ value: FfiPlayerSnapshot) -> RustBuffer {
    return FfiConverterTypeFfiPlayerSnapshot.lower(value)
}


/**
 * FFI-friendly time range (seconds-based).
 */
public struct FfiTimeRange: Equatable, Hashable {
    public let startSeconds: Double
    public let durationSeconds: Double

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(startSeconds: Double, durationSeconds: Double) {
        self.startSeconds = startSeconds
        self.durationSeconds = durationSeconds
    }

    

    
}

#if compiler(>=6)
extension FfiTimeRange: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiTimeRange: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiTimeRange {
        return
            try FfiTimeRange(
                startSeconds: FfiConverterDouble.read(from: &buf), 
                durationSeconds: FfiConverterDouble.read(from: &buf)
        )
    }

    public static func write(_ value: FfiTimeRange, into buf: inout [UInt8]) {
        FfiConverterDouble.write(value.startSeconds, into: &buf)
        FfiConverterDouble.write(value.durationSeconds, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiTimeRange_lift(_ buf: RustBuffer) throws -> FfiTimeRange {
    return try FfiConverterTypeFfiTimeRange.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiTimeRange_lower(_ value: FfiTimeRange) -> RustBuffer {
    return FfiConverterTypeFfiTimeRange.lower(value)
}


/**
 * Store configuration forwarded from platform layer to resource creation.
 */
public struct StoreOptions: Equatable, Hashable {
    public let cacheDir: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(cacheDir: String?) {
        self.cacheDir = cacheDir
    }

    

    
}

#if compiler(>=6)
extension StoreOptions: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeStoreOptions: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> StoreOptions {
        return
            try StoreOptions(
                cacheDir: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: StoreOptions, into buf: inout [UInt8]) {
        FfiConverterOptionString.write(value.cacheDir, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeStoreOptions_lift(_ buf: RustBuffer) throws -> StoreOptions {
    return try FfiConverterTypeStoreOptions.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeStoreOptions_lower(_ value: StoreOptions) -> RustBuffer {
    return FfiConverterTypeStoreOptions.lower(value)
}


/**
 * FFI-friendly error type bridging playback failures into platform bindings.
 */
public enum FfiError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case NotReady
    case ItemFailed(reason: String
    )
    case SeekFailed(reason: String
    )
    case EngineNotRunning
    case InvalidArgument(reason: String
    )
    case Internal(description: String
    )

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension FfiError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiError: FfiConverterRustBuffer {
    typealias SwiftType = FfiError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .NotReady
        case 2: return .ItemFailed(
            reason: try FfiConverterString.read(from: &buf)
            )
        case 3: return .SeekFailed(
            reason: try FfiConverterString.read(from: &buf)
            )
        case 4: return .EngineNotRunning
        case 5: return .InvalidArgument(
            reason: try FfiConverterString.read(from: &buf)
            )
        case 6: return .Internal(
            description: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case .NotReady:
            writeInt(&buf, Int32(1))
        
        
        case let .ItemFailed(reason):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(reason, into: &buf)
            
        
        case let .SeekFailed(reason):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(reason, into: &buf)
            
        
        case .EngineNotRunning:
            writeInt(&buf, Int32(4))
        
        
        case let .InvalidArgument(reason):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(reason, into: &buf)
            
        
        case let .Internal(description):
            writeInt(&buf, Int32(6))
            FfiConverterString.write(description, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiError_lift(_ buf: RustBuffer) throws -> FfiError {
    return try FfiConverterTypeFfiError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiError_lower(_ value: FfiError) -> RustBuffer {
    return FfiConverterTypeFfiError.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Typed item event dispatched through [`ItemObserver::on_event`].
 */

public enum FfiItemEvent: Equatable, Hashable {
    
    case durationChanged(seconds: Double
    )
    case bufferedDurationChanged(seconds: Double
    )
    case statusChanged(status: FfiItemStatus
    )
    case error(error: String
    )





}

#if compiler(>=6)
extension FfiItemEvent: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiItemEvent: FfiConverterRustBuffer {
    typealias SwiftType = FfiItemEvent

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiItemEvent {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .durationChanged(seconds: try FfiConverterDouble.read(from: &buf)
        )
        
        case 2: return .bufferedDurationChanged(seconds: try FfiConverterDouble.read(from: &buf)
        )
        
        case 3: return .statusChanged(status: try FfiConverterTypeFfiItemStatus.read(from: &buf)
        )
        
        case 4: return .error(error: try FfiConverterString.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiItemEvent, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .durationChanged(seconds):
            writeInt(&buf, Int32(1))
            FfiConverterDouble.write(seconds, into: &buf)
            
        
        case let .bufferedDurationChanged(seconds):
            writeInt(&buf, Int32(2))
            FfiConverterDouble.write(seconds, into: &buf)
            
        
        case let .statusChanged(status):
            writeInt(&buf, Int32(3))
            FfiConverterTypeFfiItemStatus.write(status, into: &buf)
            
        
        case let .error(error):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(error, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiItemEvent_lift(_ buf: RustBuffer) throws -> FfiItemEvent {
    return try FfiConverterTypeFfiItemEvent.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiItemEvent_lower(_ value: FfiItemEvent) -> RustBuffer {
    return FfiConverterTypeFfiItemEvent.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * FFI-friendly mirror of [`ItemStatus`].
 */

public enum FfiItemStatus: Equatable, Hashable {
    
    case unknown
    case readyToPlay
    case failed





}

#if compiler(>=6)
extension FfiItemStatus: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiItemStatus: FfiConverterRustBuffer {
    typealias SwiftType = FfiItemStatus

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiItemStatus {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .unknown
        
        case 2: return .readyToPlay
        
        case 3: return .failed
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiItemStatus, into buf: inout [UInt8]) {
        switch value {
        
        
        case .unknown:
            writeInt(&buf, Int32(1))
        
        
        case .readyToPlay:
            writeInt(&buf, Int32(2))
        
        
        case .failed:
            writeInt(&buf, Int32(3))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiItemStatus_lift(_ buf: RustBuffer) throws -> FfiItemStatus {
    return try FfiConverterTypeFfiItemStatus.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiItemStatus_lower(_ value: FfiItemStatus) -> RustBuffer {
    return FfiConverterTypeFfiItemStatus.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Typed player event dispatched through [`PlayerObserver::on_event`].
 *
 * Replaces raw integer status codes with typed enums. Swift receives
 * a single callback with a discriminated union instead of 7 separate methods.
 *
 * **Concurrency**: events may arrive from multiple threads concurrently
 * (async broadcast task + OS polling thread). Swift must handle
 * thread-safe delivery internally.
 */

public enum FfiPlayerEvent: Equatable, Hashable {
    
    case timeChanged(seconds: Double
    )
    case rateChanged(rate: Float
    )
    case currentItemChanged(itemId: String?
    )
    case statusChanged(status: FfiPlayerStatus
    )
    case timeControlStatusChanged(status: FfiTimeControlStatus
    )
    case error(error: String
    )
    case durationChanged(seconds: Double
    )
    case bufferedDurationChanged(seconds: Double
    )
    case volumeChanged(volume: Float
    )
    case muteChanged(muted: Bool
    )
    case itemDidPlayToEnd





}

#if compiler(>=6)
extension FfiPlayerEvent: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiPlayerEvent: FfiConverterRustBuffer {
    typealias SwiftType = FfiPlayerEvent

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiPlayerEvent {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .timeChanged(seconds: try FfiConverterDouble.read(from: &buf)
        )
        
        case 2: return .rateChanged(rate: try FfiConverterFloat.read(from: &buf)
        )
        
        case 3: return .currentItemChanged(itemId: try FfiConverterOptionString.read(from: &buf)
        )
        
        case 4: return .statusChanged(status: try FfiConverterTypeFfiPlayerStatus.read(from: &buf)
        )
        
        case 5: return .timeControlStatusChanged(status: try FfiConverterTypeFfiTimeControlStatus.read(from: &buf)
        )
        
        case 6: return .error(error: try FfiConverterString.read(from: &buf)
        )
        
        case 7: return .durationChanged(seconds: try FfiConverterDouble.read(from: &buf)
        )
        
        case 8: return .bufferedDurationChanged(seconds: try FfiConverterDouble.read(from: &buf)
        )
        
        case 9: return .volumeChanged(volume: try FfiConverterFloat.read(from: &buf)
        )
        
        case 10: return .muteChanged(muted: try FfiConverterBool.read(from: &buf)
        )
        
        case 11: return .itemDidPlayToEnd
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiPlayerEvent, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .timeChanged(seconds):
            writeInt(&buf, Int32(1))
            FfiConverterDouble.write(seconds, into: &buf)
            
        
        case let .rateChanged(rate):
            writeInt(&buf, Int32(2))
            FfiConverterFloat.write(rate, into: &buf)
            
        
        case let .currentItemChanged(itemId):
            writeInt(&buf, Int32(3))
            FfiConverterOptionString.write(itemId, into: &buf)
            
        
        case let .statusChanged(status):
            writeInt(&buf, Int32(4))
            FfiConverterTypeFfiPlayerStatus.write(status, into: &buf)
            
        
        case let .timeControlStatusChanged(status):
            writeInt(&buf, Int32(5))
            FfiConverterTypeFfiTimeControlStatus.write(status, into: &buf)
            
        
        case let .error(error):
            writeInt(&buf, Int32(6))
            FfiConverterString.write(error, into: &buf)
            
        
        case let .durationChanged(seconds):
            writeInt(&buf, Int32(7))
            FfiConverterDouble.write(seconds, into: &buf)
            
        
        case let .bufferedDurationChanged(seconds):
            writeInt(&buf, Int32(8))
            FfiConverterDouble.write(seconds, into: &buf)
            
        
        case let .volumeChanged(volume):
            writeInt(&buf, Int32(9))
            FfiConverterFloat.write(volume, into: &buf)
            
        
        case let .muteChanged(muted):
            writeInt(&buf, Int32(10))
            FfiConverterBool.write(muted, into: &buf)
            
        
        case .itemDidPlayToEnd:
            writeInt(&buf, Int32(11))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiPlayerEvent_lift(_ buf: RustBuffer) throws -> FfiPlayerEvent {
    return try FfiConverterTypeFfiPlayerEvent.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiPlayerEvent_lower(_ value: FfiPlayerEvent) -> RustBuffer {
    return FfiConverterTypeFfiPlayerEvent.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * FFI-friendly mirror of [`PlayerStatus`].
 */

public enum FfiPlayerStatus: Equatable, Hashable {
    
    case unknown
    case readyToPlay
    case failed





}

#if compiler(>=6)
extension FfiPlayerStatus: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiPlayerStatus: FfiConverterRustBuffer {
    typealias SwiftType = FfiPlayerStatus

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiPlayerStatus {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .unknown
        
        case 2: return .readyToPlay
        
        case 3: return .failed
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiPlayerStatus, into buf: inout [UInt8]) {
        switch value {
        
        
        case .unknown:
            writeInt(&buf, Int32(1))
        
        
        case .readyToPlay:
            writeInt(&buf, Int32(2))
        
        
        case .failed:
            writeInt(&buf, Int32(3))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiPlayerStatus_lift(_ buf: RustBuffer) throws -> FfiPlayerStatus {
    return try FfiConverterTypeFfiPlayerStatus.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiPlayerStatus_lower(_ value: FfiPlayerStatus) -> RustBuffer {
    return FfiConverterTypeFfiPlayerStatus.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * FFI-friendly mirror of [`TimeControlStatus`].
 */

public enum FfiTimeControlStatus: Equatable, Hashable {
    
    case paused
    case waitingToPlay
    case playing





}

#if compiler(>=6)
extension FfiTimeControlStatus: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiTimeControlStatus: FfiConverterRustBuffer {
    typealias SwiftType = FfiTimeControlStatus

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiTimeControlStatus {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .paused
        
        case 2: return .waitingToPlay
        
        case 3: return .playing
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiTimeControlStatus, into buf: inout [UInt8]) {
        switch value {
        
        
        case .paused:
            writeInt(&buf, Int32(1))
        
        
        case .waitingToPlay:
            writeInt(&buf, Int32(2))
        
        
        case .playing:
            writeInt(&buf, Int32(3))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiTimeControlStatus_lift(_ buf: RustBuffer) throws -> FfiTimeControlStatus {
    return try FfiConverterTypeFfiTimeControlStatus.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiTimeControlStatus_lower(_ value: FfiTimeControlStatus) -> RustBuffer {
    return FfiConverterTypeFfiTimeControlStatus.lower(value)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionDouble: FfiConverterRustBuffer {
    typealias SwiftType = Double?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterDouble.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterDouble.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeAudioPlayerItem: FfiConverterRustBuffer {
    typealias SwiftType = AudioPlayerItem?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeAudioPlayerItem.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeAudioPlayerItem.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionDictionaryStringString: FfiConverterRustBuffer {
    typealias SwiftType = [String: String]?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterDictionaryStringString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterDictionaryStringString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeAudioPlayerItem: FfiConverterRustBuffer {
    typealias SwiftType = [AudioPlayerItem]

    public static func write(_ value: [AudioPlayerItem], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeAudioPlayerItem.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [AudioPlayerItem] {
        let len: Int32 = try readInt(&buf)
        var seq = [AudioPlayerItem]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeAudioPlayerItem.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDictionaryStringString: FfiConverterRustBuffer {
    public static func write(_ value: [String: String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for (key, value) in value {
            FfiConverterString.write(key, into: &buf)
            FfiConverterString.write(value, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String: String] {
        let len: Int32 = try readInt(&buf)
        var dict = [String: String]()
        dict.reserveCapacity(Int(len))
        for _ in 0..<len {
            let key = try FfiConverterString.read(from: &buf)
            let value = try FfiConverterString.read(from: &buf)
            dict[key] = value
        }
        return dict
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_kithara_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_kithara_ffi_checksum_method_audioplayeritem_id() != 43480) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kithara_ffi_checksum_method_audioplayeritem_load() != 49002) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kithara_ffi_checksum_method_audioplayeritem_preferred_peak_bitrate() != 37617) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kithara_ffi_checksum_method_audioplayeritem_preferred_peak_bitrate_for_expensive_networks() != 36652) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kithara_ffi_checksum_method_audioplayeritem_set_observer() != 63173) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kithara_ffi_checksum_method_audioplayeritem_set_preferred_peak_bitrate() != 61806) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kithara_ffi_checksum_method_audioplayeritem_set_preferred_peak_bitrate_for_expensive_networks() != 44522) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kithara_ffi_checksum_method_audioplayeritem_set_store_options() != 11848) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kithara_ffi_checksum_method_audioplayeritem_url() != 17628) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kithara_ffi_checksum_method_itemobserver_on_event() != 60649) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kithara_ffi_checksum_method_playerobserver_on_event() != 53539) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kithara_ffi_checksum_method_seekcallback_on_complete() != 9600) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kithara_ffi_checksum_method_audioplayer_default_rate() != 41174) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kithara_ffi_checksum_method_audioplayer_insert() != 37914) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kithara_ffi_checksum_method_audioplayer_is_muted() != 23590) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kithara_ffi_checksum_method_audioplayer_items() != 26264) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kithara_ffi_checksum_method_audioplayer_pause() != 18594) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kithara_ffi_checksum_method_audioplayer_play() != 63857) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kithara_ffi_checksum_method_audioplayer_rate() != 10476) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kithara_ffi_checksum_method_audioplayer_remove() != 42802) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kithara_ffi_checksum_method_audioplayer_remove_all_items() != 32344) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kithara_ffi_checksum_method_audioplayer_seek() != 62537) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kithara_ffi_checksum_method_audioplayer_set_default_rate() != 11885) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kithara_ffi_checksum_method_audioplayer_set_muted() != 50507) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kithara_ffi_checksum_method_audioplayer_set_observer() != 3831) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kithara_ffi_checksum_method_audioplayer_set_volume() != 4642) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kithara_ffi_checksum_method_audioplayer_snapshot() != 50155) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kithara_ffi_checksum_method_audioplayer_volume() != 50555) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kithara_ffi_checksum_constructor_audioplayeritem_new() != 37818) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kithara_ffi_checksum_constructor_audioplayer_new() != 56553) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitItemObserver()
    uniffiCallbackInitPlayerObserver()
    uniffiCallbackInitSeekCallback()
    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureKitharaFfiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all