[package]
name = "kithara-ffi-web-analysis-tests"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
publish = false
autotests = false

[features]
browser = [
    "dep:js-sys",
    "dep:kithara",
    "dep:kithara-ffi",
    "dep:kithara-test-fixtures",
    "dep:wasm-bindgen",
    "dep:wasm-bindgen-test",
    "dep:web-sys",
]

[target.'cfg(target_arch = "wasm32")'.dependencies]
kithara = { workspace = true, optional = true, features = ["platform"] }
kithara-ffi = { workspace = true, optional = true, features = ["wasm"] }
kithara-test-fixtures = { workspace = true, optional = true }

js-sys = { workspace = true, optional = true }
wasm-bindgen = { workspace = true, optional = true }
wasm-bindgen-test = { workspace = true, optional = true }
web-sys = { workspace = true, optional = true }

[lints]
workspace = true

[[test]]
name = "web-analysis"
path = "tests/web_analysis.rs"
required-features = ["browser"]
