//! `IntoProbeArg` + `Probe` traits and their stock impls.
//!
//! Kept out of `lib.rs` because workspace lint policy forbids non-entry
//! items (functions, structs, traits, impls) in `lib.rs` / `mod.rs`.

use std::{
    hash::{Hash, Hasher},
    time::Duration,
};

use kithara_events::{CancelReason, RequestId, RequestPriority};
use url::Url;

/// Generated by `#[derive(kithara_probes::Probe)]` for value-type
/// probe payloads.
///
/// The derive flattens each named field into a `u64` USDT probe slot
/// (one fixed probe per struct, named after the struct in
/// `snake_case`) and a paired `tracing::event!` field. The `name`
/// argument becomes the dynamic `probe = "..."` field on the tracing
/// event so multiple call sites of the same struct can be told apart
/// by `probe_capture` consumers.
///
/// Field-level attributes:
/// - `#[probe(skip)]` — exclude this field from the wire payload.
/// - `#[probe(name = "alias")]` — rename the field on the wire (USDT
///   slot name and tracing field name).
pub trait Probe {
    /// Fire the probe associated with this value. `name` becomes the
    /// `probe` field on the tracing event so call-site granularity
    /// survives even though the USDT probe name is fixed.
    fn record_probe(&self, name: &'static str);
}

/// Convert a value of arbitrary type into the `u64` USDT wire format.
///
/// Implemented for primitive integer/bool types, the project's domain
/// enums (`RequestId`, `RequestPriority`, `CancelReason`), `Duration`
/// (saturating microseconds), `&Url` (`DefaultHasher` of the URL string),
/// and `Option<T: IntoProbeArg>`.
///
/// `Self: Copy` is required so the `#[probe]` macro can pass arguments
/// by value without forcing call-sites to clone non-`Copy` payloads.
/// Non-`Copy` references like `&Url` satisfy `Copy` because shared
/// references are `Copy`.
pub trait IntoProbeArg: Copy {
    /// Encode `self` as a u64 probe argument.
    fn into_probe_arg(self) -> u64;
}

impl IntoProbeArg for u64 {
    fn into_probe_arg(self) -> u64 {
        self
    }
}

impl IntoProbeArg for i64 {
    fn into_probe_arg(self) -> u64 {
        u64::from_ne_bytes(self.to_ne_bytes())
    }
}

impl IntoProbeArg for u32 {
    fn into_probe_arg(self) -> u64 {
        u64::from(self)
    }
}

impl IntoProbeArg for i32 {
    fn into_probe_arg(self) -> u64 {
        u64::from_ne_bytes(i64::from(self).to_ne_bytes())
    }
}

impl IntoProbeArg for usize {
    fn into_probe_arg(self) -> u64 {
        self as u64
    }
}

impl IntoProbeArg for bool {
    fn into_probe_arg(self) -> u64 {
        u64::from(self)
    }
}

impl IntoProbeArg for Duration {
    fn into_probe_arg(self) -> u64 {
        let micros = self.as_micros();
        u64::try_from(micros).unwrap_or(u64::MAX)
    }
}

impl IntoProbeArg for &Url {
    fn into_probe_arg(self) -> u64 {
        let mut hasher = std::collections::hash_map::DefaultHasher::new();
        self.as_str().hash(&mut hasher);
        hasher.finish()
    }
}

impl IntoProbeArg for RequestId {
    fn into_probe_arg(self) -> u64 {
        self.get()
    }
}

impl IntoProbeArg for RequestPriority {
    fn into_probe_arg(self) -> u64 {
        match self {
            Self::High => 0,
            Self::Low => 1,
        }
    }
}

impl IntoProbeArg for CancelReason {
    fn into_probe_arg(self) -> u64 {
        match self {
            Self::EpochCancel => 0,
            Self::PeerCancel => 1,
            Self::DownloaderShutdown => 2,
            Self::BeforeStart => 3,
        }
    }
}

impl<T: IntoProbeArg> IntoProbeArg for Option<T> {
    fn into_probe_arg(self) -> u64 {
        self.map_or(u64::MAX, |value| {
            let raw = value.into_probe_arg();
            debug_assert!(
                raw != u64::MAX,
                "Option<T>::None sentinel collides with Some(value) producing u64::MAX"
            );
            raw
        })
    }
}

/// Register all USDT probes embedded in the binary with the host
/// kernel tracer (dtrace on macOS, bpftrace on Linux). Safe to call
/// from multiple init paths — guarded by an internal `OnceLock`.
///
/// On wasm32 or without the `usdt-probes` feature this is a no-op.
pub fn register_probes() {
    imp::register();
}

#[cfg(all(feature = "usdt-probes", not(target_arch = "wasm32")))]
mod imp {
    use std::sync::OnceLock;

    static REGISTERED: OnceLock<()> = OnceLock::new();

    pub(super) fn register() {
        REGISTERED.get_or_init(|| {
            let _ = usdt::register_probes();
        });
    }
}

#[cfg(not(all(feature = "usdt-probes", not(target_arch = "wasm32"))))]
mod imp {
    pub(super) fn register() {}
}
