version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    exclude-paths:
      - crates/kithara-workspace-hack/Cargo.toml
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
    labels:
      - dependencies
      - ci
