set shell := ["bash", "-euo", "pipefail", "-c"]

ast-grep-bin := "$(command -v ast-grep || command -v sg || true)"

# Show available commands.
default:
    @just --list

# --- formatting ---

# Auto-format all Rust code.
fmt:
    cargo +nightly fmt --all

# Check formatting without modifying files.
fmt-check:
    cargo +nightly fmt --all --check

# --- checks ---

clippy:
    cargo clippy --workspace -- -D warnings

# Type-check the workspace (also used as MSRV gate in CI).
check:
    cargo check --workspace

# Audit dependencies with cargo-deny.
deny:
    cargo deny check

# Check unused dependencies (workspace-hack is auto-generated by cargo-hakari).
machete:
    cargo machete --skip-target-dir $(find crates -maxdepth 1 -mindepth 1 -not -name kithara-workspace-hack | sort) tests examples xtask

# Validate workspace architecture.
arch:
    cargo xtask quality arch

# Generate and open API docs.
doc:
    cargo doc --workspace --no-deps --open

# --- tests ---

# Cargo profile for test binaries: "dev" (debug) or "test-release" (optimised).
test-cargo-profile := env("TEST_CARGO_PROFILE", "test-release")

test *ARGS:
    cargo nextest run --workspace --exclude kithara-fuzz --cargo-profile {{test-cargo-profile}} {{ARGS}}

test-ci:
    cargo nextest run --workspace --exclude kithara-fuzz --profile ci --no-fail-fast --cargo-profile {{test-cargo-profile}}

test-doc:
    cargo test --doc --workspace --exclude kithara-fuzz

# Fast iteration: debug build, no heavy tests.
test-fast:
    cargo nextest run --workspace --exclude kithara-fuzz --profile fast -E 'not binary(suite_heavy)'

test-stress:
    cargo nextest run --workspace --exclude kithara-fuzz --profile stress -E 'binary(suite_heavy)' --cargo-profile {{test-cargo-profile}}

test-all: test test-doc

# Full project health check: lint + all tests + wasm + selenium + perf + benchmarks.
test-ultimate:
    just lint-fast
    cargo nextest run --workspace --exclude kithara-fuzz --no-fail-fast
    just test-doc
    just wasm-test
    cargo +nightly test -p kithara-integration-tests --test suite_heavy selenium -- --ignored --nocapture
    just bench-build
    cargo test -p kithara-integration-tests --features perf --release --test memory_rss -- --test-threads=1 --nocapture
    echo "==> all checks passed"

xtask-test:
    cargo test -p xtask

# --- ast-grep ---

ast-grep-blocking:
    @if [[ -z "{{ast-grep-bin}}" ]]; then \
      echo "FAILED: ast-grep is required but not installed."; \
      exit 1; \
    fi; \
    {{ast-grep-bin}} scan --config sgconfig.yml --report-style short \
      --filter '^(style.no-tests-in-lib-or-mod-rs|rust.no-thin-async-wrapper|style.no-separator-comments-toml)$'

ast-grep-advisory:
    @if [[ -z "{{ast-grep-bin}}" ]]; then \
      echo "FAILED: ast-grep is required but not installed."; \
      exit 1; \
    fi; \
    {{ast-grep-bin}} scan --config sgconfig.yml --report-style short --warning

# --- quality ---

quality-report *ARGS:
    cargo xtask quality report {{ARGS}}

quality-report-ci:
    cargo xtask quality report \
        --min-unimock-traits "${QUALITY_MIN_UNIMOCK_TRAITS:-0}" \
        --min-rstest-cases "${QUALITY_MIN_RSTEST_CASES:-0}" \
        --min-perf-test-files "${QUALITY_MIN_PERF_TEST_FILES:-0}" \
        --min-bench-targets "${QUALITY_MIN_BENCH_TARGETS:-0}" \
        --max-local-http-servers "${QUALITY_MAX_LOCAL_HTTP_SERVERS:-999}"

play-unimock-check:
    cargo xtask quality unimock-check

rstest-audit:
    cargo xtask quality rstest-audit

trait-mock-audit:
    cargo xtask quality trait-mock-audit

trait-mock-exceptions:
    cargo xtask quality trait-mock-exceptions

# Feature-powerset check (requires cargo-hack).
# kithara-wasm: wasm-only crate, not checkable on native host.
# kithara-play, kithara-app: use compile_error! to enforce required feature combinations.
# kithara-fuzz: depends on kithara-play without backend-cpal feature.
hack:
    cargo hack check --feature-powerset --no-dev-deps --depth 2 --workspace \
      --exclude kithara-wasm \
      --exclude kithara-play \
      --exclude kithara-app \
      --exclude kithara-fuzz

# Semver compatibility check (requires cargo-semver-checks).
semver:
    cargo semver-checks check-release --workspace --exclude kithara-fuzz

# --- lint composites ---

lint-fast: fmt-check clippy ast-grep-blocking arch

lint-full: lint-fast xtask-test play-unimock-check rstest-audit trait-mock-audit trait-mock-exceptions

# --- coverage ---

coverage:
    OUTPUT_DIR="${COVERAGE_OUTPUT_DIR:-./coverage}"; \
    COVERAGE_MIN="${COVERAGE_MIN:-80}"; \
    mkdir -p "$OUTPUT_DIR"; \
    cargo llvm-cov nextest \
      --workspace --exclude kithara-fuzz \
      --cargo-profile {{test-cargo-profile}} \
      --cobertura \
      --output-path "$OUTPUT_DIR/cobertura.xml" \
      --ignore-filename-regex '(tests/|examples/|benches/)' \
      --fail-under-lines "$COVERAGE_MIN"; \
    echo "==> coverage report written to $OUTPUT_DIR/cobertura.xml"; \
    echo "==> line coverage threshold: $COVERAGE_MIN%"

# --- perf & benchmarks ---

perf-test:
    cargo test -p kithara-integration-tests --features perf --release \
      -- --ignored --test-threads=1 --nocapture 2>&1 | tee perf-results.txt

# Compare perf results between baseline and candidate.
perf-compare *ARGS:
    cargo xtask perf-compare {{ARGS}}

bench-build:
    cargo bench -p kithara-integration-tests --bench abr_estimator --no-run
    cargo bench -p kithara-integration-tests --bench bufpool --no-run
    cargo bench -p kithara-integration-tests --bench refactor_hotpaths --no-run

bench-run:
    sample_size="${BENCH_SAMPLE_SIZE:-20}"; \
    cargo bench -p kithara-integration-tests --bench abr_estimator -- --sample-size "$sample_size" 2>&1 | tee bench-results.txt; \
    cargo bench -p kithara-integration-tests --bench bufpool -- --sample-size "$sample_size" 2>&1 | tee -a bench-results.txt; \
    cargo bench -p kithara-integration-tests --bench refactor_hotpaths -- --sample-size "$sample_size" 2>&1 | tee -a bench-results.txt

bench-ci:
    just bench-build; \
    if [[ "${RUN_BENCHMARKS:-0}" != "1" ]]; then \
      echo "==> benchmark execution skipped (set RUN_BENCHMARKS=1 to execute)" | tee bench-results.txt; \
      exit 0; \
    fi; \
    sample_size="${BENCH_SAMPLE_SIZE:-20}"; \
    candidate_name="${BENCH_CANDIDATE_NAME:-ci}"; \
    cargo bench -p kithara-integration-tests --bench abr_estimator \
      -- --sample-size "$sample_size" --save-baseline "$candidate_name" \
      2>&1 | tee bench-results.txt; \
    cargo bench -p kithara-integration-tests --bench bufpool \
      -- --sample-size "$sample_size" --save-baseline "$candidate_name" \
      2>&1 | tee -a bench-results.txt; \
    cargo bench -p kithara-integration-tests --bench refactor_hotpaths \
      -- --sample-size "$sample_size" --save-baseline "$candidate_name" \
      2>&1 | tee -a bench-results.txt; \
    if [[ -n "${BENCH_COMPARE_BASELINE_NAME:-}" ]]; then \
      if ! command -v critcmp >/dev/null 2>&1; then \
        echo "FAILED: critcmp is required when BENCH_COMPARE_BASELINE_NAME is set" | tee -a bench-results.txt; \
        exit 1; \
      fi; \
      baseline_name="${BENCH_COMPARE_BASELINE_NAME}"; \
      critcmp "$baseline_name" "$candidate_name" 2>&1 | tee -a bench-results.txt; \
    fi

# --- memory ---

memory-check:
    @echo "=== Tier 1: Pool-native budget tests ==="
    cargo test -p kithara-bufpool --test memory_budget
    @echo ""
    @echo "=== Tier 2: Allocation regression tests ==="
    cargo test -p kithara-bufpool --test alloc_regression -- --test-threads=1
    @echo ""
    @echo "=== Tier 3: Audio hot path zero-alloc ==="
    cargo test -p kithara-audio --test alloc_free_hotpath -- --test-threads=1
    @echo ""
    @echo "=== Tier 4: RSS budget (HLS playback) ==="
    cargo test --test memory_rss -- --test-threads=1
    @echo ""
    @echo "All memory checks passed."

# --- publish ---

# Publish all public crates to crates.io in dependency order.
publish *ARGS:
    cargo xtask publish {{ARGS}}

# --- wasm ---

# Check that key crates compile for wasm32 target.
wasm-check:
    cargo check -p kithara-wasm --target wasm32-unknown-unknown --no-default-features
    cargo check -p kithara-storage --target wasm32-unknown-unknown
    cargo check -p kithara-net --target wasm32-unknown-unknown
    cargo check -p kithara-stream --target wasm32-unknown-unknown
    cargo check -p kithara-assets --target wasm32-unknown-unknown
    cargo check -p kithara-hls --target wasm32-unknown-unknown
    cargo check -p kithara-decode --target wasm32-unknown-unknown

# Run wasm integration tests in browser.
wasm-test:
    CHROMEDRIVER="${CHROMEDRIVER:-chromedriver}" \
    WASM_BINDGEN_TEST_TIMEOUT=300 \
    WASM_BINDGEN_USE_BROWSER=1 \
    cargo +nightly test --target wasm32-unknown-unknown \
        -p kithara-integration-tests

# Build wasm demo app.
wasm-build:
    cargo xtask wasm build

wasm-size-check:
    @toolchain="${WASM_SLIM_TOOLCHAIN:-nightly}"; \
    if command -v wasm-slim >/dev/null 2>&1; then \
        slim_cmd="wasm-slim"; \
    elif command -v cargo-wasm-slim >/dev/null 2>&1; then \
        slim_cmd="cargo wasm-slim"; \
    else \
        echo "wasm-slim is not installed"; exit 2; \
    fi; \
    mkdir -p target; \
    ln -sfn ../../target crates/kithara-wasm/target; \
    cd crates/kithara-wasm && \
    RUSTUP_TOOLCHAIN="$toolchain" $slim_cmd build --check --no-emoji --json > ../../target/wasm-slim-result.json; \
    echo "wasm-slim report: target/wasm-slim-result.json"

# --- android ---

# Build Android JNI libraries and Kotlin bindings.
android *ARGS:
    cargo xtask android build {{ARGS}}

# Build release AAR (includes JNI libs and Kotlin bindings).
android-aar:
    cargo xtask android build --profile release
    cd android && ./gradlew :lib:assembleRelease -Pkithara.release=true -x generateKitharaFfi
    @echo "==> AAR: android/lib/build/outputs/aar/lib-release.aar"
# --- apple ---

# Build XCFramework for Apple platforms.
xcframework *ARGS:
    cargo xtask apple build {{ARGS}}

# Build XCFramework (debug) and run the Swift demo app.
apple-demo:
    just xcframework --profile debug
    cd apple && KITHARA_LOCAL_DEV=1 swift run KitharaDemo

# Build XCFramework, zip, and compute checksum for SPM distribution.
release-apple:
    just xcframework
    cd apple && zip -ry /tmp/KitharaFFIInternal.xcframework.zip KitharaFFIInternal.xcframework
    swift package compute-checksum /tmp/KitharaFFIInternal.xcframework.zip
