// swift-tools-version: 6.0

import Foundation
import PackageDescription

// Updated automatically by CI on release.
let version = "0.0.1"
let checksum = "b93ef2fc533685aa8fba33a575a0c56328f2cd7fadb25a7aaff5cf880999fccb"

// KITHARA_LOCAL_DEV       — use locally built xcframework (for development).
// KITHARA_BINARY_BASE_URL — override binary download host (for GitLab mirror).
//
// GitHub (default): https://github.com/zvuk/kithara/releases/download
// GitLab:           https://gitlab.zvq.me/api/v4/projects/<id>/packages/generic/kithara
let useLocalBinary = ProcessInfo.processInfo.environment["KITHARA_LOCAL_DEV"] != nil

let binaryTarget: Target
if useLocalBinary {
    binaryTarget = .binaryTarget(name: "KitharaFFIInternal", path: "apple/KitharaFFIInternal.xcframework")
} else {
    let defaultBaseURL = "https://github.com/zvuk/kithara/releases/download"
    let baseURL = ProcessInfo.processInfo.environment["KITHARA_BINARY_BASE_URL"] ?? defaultBaseURL
    binaryTarget = .binaryTarget(
        name: "KitharaFFIInternal",
        url: "\(baseURL)/v\(version)/KitharaFFIInternal.xcframework.zip",
        checksum: checksum
    )
}

let package = Package(
    name: "Kithara",
    platforms: [.iOS(.v16), .macOS(.v13)],
    products: [
        .library(name: "Kithara", targets: ["Kithara"]),
        .library(name: "KitharaFFI", targets: ["KitharaFFI"]),
    ],
    targets: [
        // Low-level static library from Rust (generated by cargo-swift).
        binaryTarget,

        // UniFFI-generated Swift bindings.
        .target(
            name: "KitharaFFI",
            dependencies: [
                .target(name: "KitharaFFIInternal"),
            ],
            path: "apple/Sources/KitharaFFI",
            linkerSettings: [
                .linkedFramework("AudioToolbox"),
                .linkedFramework("CoreAudio"),
                .linkedFramework("Security"),
                .linkedFramework("SystemConfiguration"),
            ]
        ),

        // Swifty public API layer.
        .target(
            name: "Kithara",
            dependencies: ["KitharaFFI"],
            path: "apple/Sources/Kithara"
        ),

        .testTarget(
            name: "KitharaTests",
            dependencies: ["Kithara"],
            path: "apple/Tests/KitharaTests"
        ),
    ]
)
