// swift-tools-version: 6.0

import Foundation
import PackageDescription

// Updated automatically by CI on release.
let version = "0.0.1-alpha3"
let checksum = "fcbdb1ba92eb17987e50155efe4851d6ba195b4a02e74ff40ed1bd567e9fb191"

// KITHARA_LOCAL_DEV       — use locally built xcframework (for development).
// KITHARA_BINARY_BASE_URL — override binary download host (for GitLab mirror).
//
// GitHub (default): https://github.com/zvuk/kithara/releases/download
// GitLab:           https://gitlab.zvq.me/api/v4/projects/<id>/packages/generic/kithara
let environment = ProcessInfo.processInfo.environment
let localBinaryRelativePath = "apple/KitharaFFIInternal.xcframework"
let packageDirectory = URL(fileURLWithPath: #filePath).deletingLastPathComponent()
let localBinaryAbsolutePath = packageDirectory
    .appendingPathComponent(localBinaryRelativePath)
    .path
let localBinaryExists = FileManager.default.fileExists(atPath: localBinaryAbsolutePath)

func boolOverride(_ value: String?) -> Bool? {
    guard let value else {
        return nil
    }

    switch value.trimmingCharacters(in: .whitespacesAndNewlines).lowercased() {
    case "1", "true", "yes":
        return true
    case "0", "false", "no":
        return false
    default:
        return nil
    }
}

let localDevOverride = boolOverride(environment["KITHARA_LOCAL_DEV"])
let useLocalBinary = localDevOverride ?? localBinaryExists

let binaryTarget: Target
if useLocalBinary {
    guard localBinaryExists else {
        fatalError(
            """
            KITHARA_LOCAL_DEV requires a local XCFramework, but the file was not found:
            \(localBinaryAbsolutePath)

            Build it with:
            cargo xtask apple build
            """
        )
    }

    binaryTarget = .binaryTarget(
        name: "KitharaFFIInternal",
        path: localBinaryRelativePath
    )
} else {
    let defaultBaseURL = "https://github.com/zvuk/kithara/releases/download"
    let baseURL = environment["KITHARA_BINARY_BASE_URL"] ?? defaultBaseURL
    binaryTarget = .binaryTarget(
        name: "KitharaFFIInternal",
        url: "\(baseURL)/v\(version)/KitharaFFIInternal.xcframework.zip",
        checksum: checksum
    )
}

let package = Package(
    name: "Kithara",
    platforms: [.iOS(.v16), .macOS(.v13)],
    products: [
        .library(name: "Kithara", targets: ["Kithara"]),
        .library(name: "KitharaFFI", targets: ["KitharaFFI"]),
        .library(name: "KitharaRx", targets: ["KitharaRx"]),
    ],
    dependencies: [
        .package(url: "https://github.com/ReactiveX/RxSwift.git", from: "6.6.0"),
        .package(url: "https://github.com/swiftlang/swift-docc-plugin.git", from: "1.4.0"),
    ],
    targets: [
        // Low-level static library from Rust (generated by cargo-swift).
        binaryTarget,

        // UniFFI-generated Swift bindings.
        .target(
            name: "KitharaFFI",
            dependencies: [
                .target(name: "KitharaFFIInternal"),
            ],
            path: "apple/Sources/KitharaFFI",
            linkerSettings: [
                .linkedFramework("AudioToolbox"),
                .linkedFramework("CoreAudio"),
                .linkedFramework("Security"),
                .linkedFramework("SystemConfiguration"),
            ]
        ),

        // Swifty public API layer.
        .target(
            name: "Kithara",
            dependencies: ["KitharaFFI"],
            path: "apple/Sources/Kithara"
        ),

        // Optional RxSwift bridge over Kithara's Combine publishers.
        .target(
            name: "KitharaRx",
            dependencies: [
                "Kithara",
                .product(name: "RxSwift", package: "RxSwift"),
            ],
            path: "apple/Sources/KitharaRx"
        ),

        .testTarget(
            name: "KitharaTests",
            dependencies: ["Kithara"],
            path: "apple/Tests/KitharaTests"
        ),
    ]
)
