import {
    Button,
    Slider,
    StandardListView,
    HorizontalBox,
    VerticalBox,
    TabWidget,
} from "std-widgets.slint";
import { Playback } from "components/playback.slint";
import { Header } from "components/header.slint";
import { Footer } from "components/footer.slint";
import { Volume } from "components/volume.slint";
import { Equalizer, EqBandModel } from "components/equalizer.slint";
import { DJ } from "components/dj.slint";
import { Playlist, PlaylistTrackModel } from "components/playlist.slint";
import { Settings, AudioQualityModel } from "components/settings.slint";
import { AudioQuality } from "components/utils.slint";

export component AppWindow inherits Window {
    in-out property <[PlaylistTrackModel]> playlist <=> playlist.tracks;
    in-out property <[EqBandModel]> eq_bands <=> eq.bands;
    in-out property <[AudioQualityModel]> qualities <=> settings.qualities;
    in-out property <AudioQuality> selected-quality <=> settings.selected-quality;
    in-out property <int> current-track <=> playlist.current-track;
    in-out property <bool> playing <=> playback.is-playing;
    in-out property <bool> shuffle-active <=> playback.shuffle-active;
    in-out property <bool> repeat-active <=> playback.repeat-active;
    in-out property <float> crossfade <=> settings.crossfade;
    in-out property <float> position <=> header.position;
    in-out property <float> duration <=> header.duration;
    in-out property <float> volume <=> volume.value;
    in-out property <float> pan;
    in-out property <bool> is-user-seeking: false;

    callback seek <=> header.seek;
    callback play <=> playback.play;
    callback next <=> playback.next;
    callback prev <=> playback.prev;
    callback toggle-shuffle <=> playback.toggle-shuffle;
    callback toggle-repeat <=> playback.toggle-repeat;
    callback update-volume <=> volume.changed;
    callback select-track <=> playlist.select-track;
    callback toggle-quality <=> settings.toggle-quality;
    callback update-crossfade <=> settings.update-crossfade;
    callback eq-band-changed <=> eq.band-changed;

    background: @linear-gradient(0deg, #fffff2, #fff8f8);
    min-height: 320px;
    min-width: 320px;
    max-height: 1320px;
    max-width: 540px;
    preferred-height: 734px;
    preferred-width: 448px;
    title: "Kithara";

    VerticalLayout {
        alignment: stretch;
        padding: 0px;
        spacing: 0px;

        VerticalBox {
            padding: 0px;
            header := Header {
                height: 184px;
                text <=> root.title;
            }

            playback := Playback {
                height: 74px;
            }

            volume := Volume {
                height: 57px;
            }
        }

        VerticalBox {
            vertical-stretch: 1;
            padding: 0px;
            TabWidget {
                Tab {
                    title: "Playlist";
                    playlist := Playlist { }
                }

                Tab {
                    title: "DJ";
                    dj := DJ { }
                }

                Tab {
                    title: "Equalizer";
                    eq := Equalizer { }
                }

                Tab {
                    title: "Settings";
                    settings := Settings { }
                }
            }
        }

        VerticalBox {
            padding: 0px;
            footer := Footer {
                height: 33px;
                crossfade: crossfade;
                selected-quality: selected-quality;
            }
        }
    }
}
