[package]
name = "kithara-sync-tests"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
publish = false
autotests = false

[features]
default = ["client-reqwest", "tls-rustls", "usdt"]
client-reqwest = ["kithara/client-reqwest"]
client-wreq = ["kithara/client-wreq"]
tls-rustls = ["kithara/tls-rustls"]
tls-native = ["kithara/tls-native"]
flash = ["kithara/flash", "kithara-integration-tests/flash"]
load = ["kithara-integration-tests/load"]
no-block = ["kithara/no-block", "kithara-integration-tests/no-block"]
usdt = ["kithara/usdt", "kithara-integration-tests/usdt"]
apple-fused-src = ["kithara/apple-fused-src"]

[dependencies]
kithara = { workspace = true, features = ["platform"] }
kithara-integration-tests = { workspace = true, features = ["all"] }
kithara-test-fixtures = { workspace = true, default-features = false, features = ["encoded", "library", "packaged", "rhythm", "signal"] }
kithara-test-utils = { workspace = true }

futures = { workspace = true }

[target.'cfg(target_os = "android")'.dependencies]
kithara-test-dylib = { workspace = true }

[lints]
workspace = true

[[test]]
name = "sync"
path = "tests/suite.rs"
