import { HorizontalBox, VerticalBox } from "std-widgets.slint";
import { Progress } from "progress.slint";

export component Header inherits VerticalLayout {
    in-out property <float> duration <=> progress.duration;
    in-out property <float> position <=> progress.position;
    in property <string> text <=> label.text;

    callback seek <=> progress.seek;

    VerticalBox {
        HorizontalLayout {
            HorizontalBox {
                padding: 0px;
                label := Text {
                    font-size: 22px;
                    horizontal-alignment: center;
                    color: #292929;
                }
            }
        }
    }

    VerticalBox {
        padding: 0px;
        progress := Progress { }
    }
}
