import { Icons as LucideIcons } from "@lucide";

export global Icons {
    out property <image> AudioLinesIcon <=> LucideIcons.AudioLinesIcon;
    out property <image> ClockIcon <=> LucideIcons.ClockIcon;
    out property <image> DownloadIcon <=> LucideIcons.DownloadIcon;
    out property <image> ImageIcon <=> LucideIcons.ImageIcon;
    out property <image> MusicIcon <=> LucideIcons.MusicIcon;
    out property <image> PauseIcon <=> LucideIcons.PauseIcon;
    out property <image> PlayIcon <=> LucideIcons.PlayIcon;
    out property <image> RepeatIcon <=> LucideIcons.RepeatIcon;
    out property <image> SettingsIcon <=> LucideIcons.SettingsIcon;
    out property <image> ShuffleIcon <=> LucideIcons.ShuffleIcon;
    out property <image> SkipBackIcon <=> LucideIcons.SkipBackIcon;
    out property <image> SkipForwardIcon <=> LucideIcons.SkipForwardIcon;
    out property <image> SlidersVerticalIcon <=> LucideIcons.SlidersVerticalIcon;
    out property <image> Volume2Icon <=> LucideIcons.Volume2Icon;
}
