import { ListView, HorizontalBox, VerticalBox } from "std-widgets.slint";
import { Icons } from "icons.slint";
import { Button } from "button.slint";

export enum PlaylistState {
    Idle,
    Loaded,
    Playing,
    Error,
}

export struct PlaylistTrackModel {
    path: string,
    title: string,
    artist: string,
    duration: float,
    state: PlaylistState,
}

component PlaylistItem inherits Rectangle {
    in property <PlaylistTrackModel> track;
    in property <bool> probed: track.artist != "" && track.title != "";
    in property <bool> error: track.state == PlaylistState.Error;
    in property <bool> selected;
    in property <int> index;

    callback clicked <=> touch.clicked;
    background: error ? red : (selected ? yellow : transparent);

    HorizontalLayout {
        HorizontalBox {
            height: 40px;
            padding: 0;

            if track.state == PlaylistState.Playing: Button {
                height: 100%;
                width: self.height;
                icon: Icons.AudioLinesIcon;
            }
            if track.state != PlaylistState.Playing: Text {
                height: 100%;
                width: self.height;
                text: @tr("{0}", index);
            }

            if probed: VerticalLayout {
                VerticalBox {
                    padding: 0;
                    Text {
                        height: 20px;
                        text: track.title;
                    }

                    Text {
                        height: 20px;
                        text: track.artist;
                    }
                }
            }

            if !probed: Text {
                text: track.path;
            }

            @children
        }
    }

    touch := TouchArea { }
}

export component Playlist inherits ListView {
    in-out property <[PlaylistTrackModel]> tracks;
    in-out property <int> current-track;

    callback select-track(int);

    for track[index] in tracks: PlaylistItem {
        track: track;
        index: index;
        selected: index == root.current-track;
        clicked => {
            root.select-track(index);
        }
    }
}
