import {
    Slider,
    HorizontalBox,
    VerticalBox,
} from "std-widgets.slint";
import { Icons } from "icons.slint";
import { Button } from "./button.slint";

export component Progress inherits VerticalLayout {
    in-out property <float> duration <=> slider.maximum;
    in-out property <float> position <=> slider.value;

    callback seek <=> slider.changed;

    function minutes(duration: float) -> int {
        return Math.floor(duration / 60);
    }

    function seconds(duration: float) -> int {
        return Math.mod(duration, 60);
    }

    function duration-format(duration: float) -> string {
        return @tr("{0}:{1}", minutes(duration), seconds(duration));
    }

    VerticalBox {
        padding: 0px;
        slider := Slider {
            minimum: 0;
        }
    }

    VerticalBox {
        padding: 0px;
        HorizontalLayout {
            alignment: stretch;
            HorizontalBox {
                Text {
                    text: duration-format(slider.value);
                    horizontal-alignment: left;
                }

                Text {
                    text: duration-format(slider.maximum);
                    horizontal-alignment: right;
                }
            }
        }
    }
}
