import {
    ScrollView,
    VerticalBox,
    HorizontalBox,
    CheckBox,
    Slider,
} from "std-widgets.slint";
import { AudioQuality, Utils } from "utils.slint";

export struct AudioQualityModel {
    label: string,
    value: AudioQuality,
    checked: bool,
}

component SettingCheckbox inherits HorizontalLayout {
    in property <string> label <=> checkbox.text;
    in-out property <bool> checked <=> checkbox.checked;

    callback toggled <=> checkbox.toggled;

    HorizontalBox {
        padding: 0;
        checkbox := CheckBox { }
    }
}

component SettingSlider inherits VerticalLayout {
    in-out property <float> value <=> slider.value;
    in property <float> minimum <=> slider.minimum;
    in property <float> maximum <=> slider.maximum;
    in property <string> label <=> label.text;

    callback changed <=> slider.changed;

    VerticalBox {
        padding: 0;
        label := Text { }

        slider := Slider { }
    }
}

component SettingsGroup inherits VerticalLayout {
    in property <string> title <=> label.text;

    VerticalBox {
        padding: 0;
        label := Text { }
    }

    @children
}

component AudioQualitySettings inherits SettingsGroup {
    in-out property <AudioQuality> value;
    in-out property <[AudioQualityModel]> qualities: [
        {
            label: Utils.quality-to-string(AudioQuality.Low),
            value: AudioQuality.Low,
            checked: value == AudioQuality.Low
        },
        {
            label: Utils.quality-to-string(AudioQuality.Medium),
            value: AudioQuality.Medium,
            checked: value == AudioQuality.Medium
        },
        {
            label: Utils.quality-to-string(AudioQuality.High),
            value: AudioQuality.High,
            checked: value == AudioQuality.High
        },
        {
            label: Utils.quality-to-string(AudioQuality.Lossless),
            value: AudioQuality.Lossless,
            checked: value == AudioQuality.Lossless
        }
    ];

    callback toggled(value: AudioQuality);

    for model[index] in qualities: SettingCheckbox {
        label: model.label;
        checked: model.checked;
        toggled => {
            root.value = model.value;
            toggled(model.value);
        }
    }
}

component CrossfadeSettings inherits SettingsGroup {
    in-out property <float> value <=> slider.value;
    in property <float> minimum <=> slider.minimum;
    in property <float> maximum <=> slider.maximum;

    callback changed <=> slider.changed;

    slider := SettingSlider {
        label: "Duration";
    }
}

export component Settings inherits ScrollView {
    in-out property <[AudioQualityModel]> qualities <=> quality.qualities;
    in-out property <AudioQuality> selected-quality <=> quality.value;
    in-out property <float> crossfade <=> crossfade.value;

    callback toggle-quality <=> quality.toggled;
    callback update-crossfade <=> crossfade.changed;

    VerticalLayout {
        VerticalBox {
            padding: 0;
            quality := AudioQualitySettings {
                title: "Audio Quality";
            }

            crossfade := CrossfadeSettings {
                title: "Crossfade";
                minimum: 0.0;
                maximum: 30.0;
            }
        }
    }
}
