export enum AudioQuality {
    Low,
    Medium,
    High,
    Lossless
}

export global Utils {
    public pure function quality-to-string(quality: AudioQuality) -> string {
        if quality == AudioQuality.Medium {
            return "Medium";
        }
        if quality == AudioQuality.High {
            return "High";
        }
        if quality == AudioQuality.Lossless {
            return "Lossless";
        }
        return "Low";
    }
}
