import {
    Slider,
    HorizontalBox,
    VerticalBox,
} from "std-widgets.slint";
import { Icons } from "icons.slint";
import { Button } from "button.slint";

export component Volume inherits HorizontalLayout {
    in-out property <float> value <=> slider.value;
    in property <length> button-size: 24px;

    callback changed <=> slider.changed;

    function volume(value: float) -> int {
        return min(max(value * 100, 0), 100);
    }

    function volume_format(value: float) -> string {
        return @tr("{0}", volume(value));
    }

    HorizontalBox {
        mute := Button {
            height: root.button-size;
            width: root.button-size;
            icon: Icons.Volume2Icon;
            icon-color: #eee;
        }

        slider := Slider {
            minimum: 0;
            maximum: 1;
        }

        Text {
            text: volume_format(slider.value);
        }
    }
}
