[package]
name = "kithara-events-tests"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
publish = false
autotests = false

[package.metadata.cargo-machete]
ignored = ["kithara-test-utils"]

[features]
default = ["client-reqwest", "tls-rustls"]
client-reqwest = ["kithara/client-reqwest"]
client-wreq = ["kithara/client-wreq"]
tls-rustls = ["kithara/tls-rustls"]
tls-native = ["kithara/tls-native"]
flash = ["kithara/flash"]
no-block = ["kithara/no-block"]

[dependencies]
kithara = { workspace = true, features = ["events", "platform", "probe"] }

kithara-test-utils = { workspace = true, features = ["hang", "mock", "probe"] }

[lints]
workspace = true

[[test]]
name = "events"
path = "tests/suite.rs"
