// swift-tools-version: 6.0

import Foundation
import PackageDescription

let useLocalBinary = ProcessInfo.processInfo.environment["KITHARA_LOCAL_DEV"] != nil

let binaryTarget: Target = useLocalBinary
    ? .binaryTarget(name: "KitharaFFIInternal", path: "KitharaFFIInternal.xcframework")
    : .binaryTarget(
        name: "KitharaFFIInternal",
        url: "https://github.com/zvuk/kithara/releases/download/v0.1.0/KitharaFFIInternal.xcframework.zip",
        checksum: "9f1245e473fa803608b292a5abe6ab8c5edd217297c162b8b3def1dd6b44699e"
      )

let package = Package(
    name: "Kithara",
    platforms: [.iOS(.v16), .macOS(.v13)],
    products: [
        .library(name: "Kithara", targets: ["Kithara"]),
        .library(name: "KitharaFFI", targets: ["KitharaFFI"]),
    ],
    targets: [
        // Low-level static library from Rust (generated by cargo-swift).
        binaryTarget,

        // UniFFI-generated Swift bindings.
        .target(
            name: "KitharaFFI",
            dependencies: [
                .target(name: "KitharaFFIInternal"),
            ],
            path: "Sources/KitharaFFI",
            linkerSettings: [
                .linkedFramework("AudioToolbox"),
                .linkedFramework("CoreAudio"),
                .linkedFramework("Security"),
                .linkedFramework("SystemConfiguration"),
            ]
        ),

        // Swifty public API layer.
        .target(
            name: "Kithara",
            dependencies: ["KitharaFFI"],
            path: "Sources/Kithara"
        ),

        // Demo app (macOS only, for quick testing).
        .executableTarget(
            name: "KitharaDemo",
            dependencies: ["Kithara"],
            path: "Examples/KitharaDemo/Sources"
        ),

        .testTarget(
            name: "KitharaTests",
            dependencies: ["Kithara"],
            path: "Tests/KitharaTests"
        ),
    ]
)
