// swift-tools-version: 6.0

import PackageDescription

let package = Package(
    name: "Kithara",
    platforms: [.iOS(.v16), .macOS(.v13)],
    products: [
        .library(name: "Kithara", targets: ["Kithara"]),
        .library(name: "KitharaFFI", targets: ["KitharaFFI"]),
    ],
    targets: [
        // Low-level static library from Rust (generated by cargo-swift).
        .binaryTarget(
            name: "KitharaFFIInternal",
            path: "KitharaFFIInternal.xcframework"
        ),

        // UniFFI-generated Swift bindings.
        .target(
            name: "KitharaFFI",
            dependencies: [
                .target(name: "KitharaFFIInternal"),
            ],
            path: "Sources/KitharaFFI",
            linkerSettings: [
                .linkedFramework("AudioToolbox"),
                .linkedFramework("CoreAudio"),
                .linkedFramework("Security"),
                .linkedFramework("SystemConfiguration"),
            ]
        ),

        // Swifty public API layer.
        .target(
            name: "Kithara",
            dependencies: ["KitharaFFI"],
            path: "Sources/Kithara"
        ),

        .testTarget(
            name: "KitharaTests",
            dependencies: ["Kithara"],
            path: "Tests/KitharaTests"
        ),
    ]
)
