// @generated by `just tooling xtask config project`; do not edit.

/// HTTP method used to probe an HLS segment's exact size.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[cfg_attr(any(feature = "uniffi", feature = "uniffi-web"), derive(uniffi::Enum))]
pub enum FfiSizeProbeMethod {
    /// Probe with HTTP HEAD.
    Head,
    /// Probe with a one-byte ranged GET.
    RangeGet,
    /// Reserved value rejected when configuring an item.
    Unknown,
}

impl TryFrom<FfiSizeProbeMethod> for kithara_hls::SizeProbeMethod {
    type Error = crate::types::FfiError;

    fn try_from(value: FfiSizeProbeMethod) -> Result<Self, Self::Error> {
        match value {
            FfiSizeProbeMethod::Head => Ok(Self::Head),
            FfiSizeProbeMethod::RangeGet => Ok(Self::RangeGet),
            FfiSizeProbeMethod::Unknown => Err(crate::types::FfiError::InvalidArgument {
                reason: "unknown HLS size probe method".into(),
            }),
        }
    }
}

/// Optional File stream settings for one item.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
#[cfg_attr(
    any(feature = "uniffi", feature = "uniffi-web"),
    derive(uniffi::Record)
)]
pub struct FfiFileSourceSettings {
    /// Max bytes the downloader may be ahead of the reader before it pauses.
    /// `None` permits fetching the whole file. `Some(0)` fetches only through
    /// the current read request.
    /// Accepted range: 0..=8388608 bytes.
    pub look_ahead_bytes: Option<u64>,
    /// Ring depth for the decode-core to shell reader-event hand-off. A decode
    /// pass emits at most one progress event per decoded chunk, so the default
    /// bounds the worst-case post-seek skip burst without blocking the decode
    /// core.
    /// Accepted range: 1..=4096.
    pub reader_event_capacity: Option<u32>,
}

impl TryFrom<FfiFileSourceSettings> for kithara_file::FileConfigPatch {
    type Error = crate::types::FfiError;

    fn try_from(value: FfiFileSourceSettings) -> Result<Self, Self::Error> {
        let mut patch = Self::default();
        if let Some(input) = value.look_ahead_bytes {
            if input > 8388608 {
                return Err(crate::types::FfiError::InvalidArgument {
                    reason: "FileConfig.look_ahead_bytes must be in 0..=8388608".into(),
                });
            }
            patch.look_ahead_bytes = Some(Some(input));
        }
        if let Some(input) = value.reader_event_capacity {
            if input == 0 || input > 4096 {
                return Err(crate::types::FfiError::InvalidArgument {
                    reason: "FileConfig.reader_event_capacity must be in 1..=4096".into(),
                });
            }
            patch.reader_event_capacity = Some(input as usize);
        }
        Ok(patch)
    }
}

/// Optional Hls stream settings for one item.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
#[cfg_attr(
    any(feature = "uniffi", feature = "uniffi-web"),
    derive(uniffi::Record)
)]
pub struct FfiHlsSourceSettings {
    /// Max bytes the downloader may be ahead of the reader before it pauses.
    /// `None` falls back to a ~2 `MiB` cap at the consumer site —
    /// production HLS streams need a downloader backpressure cap.
    /// `Some(0)` prevents prefetch beyond the reader position.
    /// Accepted range: 0..=8388608 bytes.
    pub look_ahead_bytes: Option<u64>,
    /// Method used by on-demand exact-size probes. Segment-aware fMP4 decode
    /// never issues these probes; file-like paths use them after a seek needs
    /// exact prefix offsets.
    pub size_probe_method: Option<FfiSizeProbeMethod>,
    /// Acquire attempts a planned segment slot gets before the dispatch
    /// settles it terminally. A requeue is re-dispatched on the peer's next
    /// poll, so this counts dispatch rounds, not wall-clock time. A tmp held
    /// by a live sibling writer is exempt — that holder always settles and
    /// releases, so its retry resolves on its own.
    /// Accepted range: 0..=255.
    pub acquire_attempt_budget: Option<u32>,
    /// Max segments to download per step. Three keep the fetcher busy across
    /// one round-trip without planning further ahead than a look-ahead cap
    /// would allow anyway.
    /// Accepted range: 1..=64.
    pub download_batch_size: Option<u32>,
}

impl TryFrom<FfiHlsSourceSettings> for kithara_hls::HlsConfigPatch {
    type Error = crate::types::FfiError;

    fn try_from(value: FfiHlsSourceSettings) -> Result<Self, Self::Error> {
        let mut patch = Self::default();
        if let Some(input) = value.look_ahead_bytes {
            if input > 8388608 {
                return Err(crate::types::FfiError::InvalidArgument {
                    reason: "HlsConfig.look_ahead_bytes must be in 0..=8388608".into(),
                });
            }
            patch.look_ahead_bytes = Some(Some(input));
        }
        if let Some(input) = value.size_probe_method {
            patch.size_probe_method = Some(input.try_into()?);
        }
        if let Some(input) = value.acquire_attempt_budget {
            if input > 255 {
                return Err(crate::types::FfiError::InvalidArgument {
                    reason: "HlsConfig.acquire_attempt_budget must be in 0..=255".into(),
                });
            }
            patch.acquire_attempt_budget =
                Some(
                    u8::try_from(input).map_err(|_| crate::types::FfiError::InvalidArgument {
                        reason: "HlsConfig.acquire_attempt_budget exceeds u8".into(),
                    })?,
                );
        }
        if let Some(input) = value.download_batch_size {
            if input == 0 || input > 64 {
                return Err(crate::types::FfiError::InvalidArgument {
                    reason: "HlsConfig.download_batch_size must be in 1..=64".into(),
                });
            }
            patch.download_batch_size = Some(input as usize);
        }
        Ok(patch)
    }
}

/// Per-item source settings, applied before opening the file or HLS stream.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
#[cfg_attr(
    any(feature = "uniffi", feature = "uniffi-web"),
    derive(uniffi::Record)
)]
pub struct FfiSourceSettings {
    /// File-stream settings, when supplied.
    pub file: Option<FfiFileSourceSettings>,
    /// HLS-stream settings, when supplied.
    pub hls: Option<FfiHlsSourceSettings>,
}
