// @generated by `just tooling xtask config project`; do not edit.
use super::config_generated::FfiLimiterConfig;

/// Settings fixed for the lifetime of the process-wide audio host.
#[derive(Clone, Copy, Debug, PartialEq)]
#[cfg_attr(
    any(feature = "uniffi", feature = "uniffi-web"),
    derive(uniffi::Record)
)]
#[cfg_attr(target_arch = "wasm32", wasm_bindgen::prelude::wasm_bindgen)]
pub struct FfiHostConfig {
    /// Initial device sample-rate hint in hertz; `Host::set_sample_rate` moves it later.
    pub sample_rate_hint: u32,
    /// Optional native output callback size in frames. `None` preserves the backend default.
    pub output_block_frames: Option<u32>,
    /// Session output limiter policy prepared when the host starts.
    pub limiter: FfiLimiterConfig,
}

impl FfiHostConfig {
    pub(crate) fn into_domain<S>(
        self,
    ) -> Result<kithara::host::HostConfig<S>, crate::types::FfiError> {
        let sample_rate_hint =
            std::num::NonZeroU32::new(self.sample_rate_hint).ok_or_else(|| {
                crate::types::FfiError::InvalidArgument {
                    reason: "host sample rate must be greater than zero".to_owned(),
                }
            })?;
        let output_block_frames = self
            .output_block_frames
            .map(|frames| {
                std::num::NonZeroU32::new(frames).ok_or_else(|| {
                    crate::types::FfiError::InvalidArgument {
                        reason: "host output block size must be greater than zero".to_owned(),
                    }
                })
            })
            .transpose()?;
        let limiter = self.limiter.try_into()?;
        Ok(kithara::host::HostConfig::builder()
            .sample_rate_hint(sample_rate_hint)
            .maybe_output_block_frames(output_block_frames)
            .limiter(limiter)
            .build())
    }
}
