[package]
name = "kithara-harness-tests"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
publish = false
autotests = false

[package.metadata.cargo-machete]
ignored = ["serial_test"]

[features]
harness = []
flash = ["kithara/flash", "kithara-integration-tests/flash"]
no-block = ["kithara/no-block", "kithara-integration-tests/no-block"]

[dependencies]
kithara = { workspace = true, features = ["platform"] }
kithara-integration-tests = { workspace = true, features = ["all"] }
kithara-test-dylib = { workspace = true }
kithara-test-utils = { workspace = true, features = ["usdt", "hang", "mock"] }
serial_test = { workspace = true }
tempfile = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
kithara = { workspace = true, features = ["mock", "offline", "signal"] }
kithara-test-fixtures = { workspace = true, default-features = false, features = ["signal"] }

cochlea-features = { workspace = true }
reqwest = { workspace = true, features = ["rustls"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = { workspace = true }
wasm-bindgen = { workspace = true }
web-sys = { workspace = true }

[lints]
workspace = true

[[test]]
name = "suite_light"
path = "tests/suite_light.rs"

[[test]]
name = "suite_harness"
path = "tests/suite_harness.rs"
required-features = ["harness"]
