use std::fmt::Write as _;

use anyhow::{Result, bail, ensure};

use super::discover::{RegisteredField, Registration};

pub(super) fn render(registrations: &[Registration]) -> Result<String> {
    let delegates: Vec<_> = registrations
        .iter()
        .filter(|registration| registration.kind == "delegate" && registration.sdk)
        .collect();
    ensure!(
        !delegates.is_empty(),
        "no SDK config operations are registered"
    );
    let mut output = String::from(
        "// @generated by `just tooling xtask config project`; do not edit.\n\
         use kithara::play::{EqBandConfig, FilterKind, GainDb};\n\n\
         /// Filter response applied by one equalizer band.\n\
         #[derive(Clone, Copy, Debug, PartialEq, Eq)]\n\
         #[cfg_attr(any(feature = \"uniffi\", feature = \"uniffi-web\"), derive(uniffi::Enum))]\n\
         pub enum FfiEqFilterKind {\n\
         \x20\x20\x20\x20LowShelf,\n\
         \x20\x20\x20\x20Peaking,\n\
         \x20\x20\x20\x20HighShelf,\n\
         }\n\n",
    );
    for delegate in delegates {
        ensure!(
            delegate.package == "kithara-play"
                && delegate.property.as_deref() == Some("eq_layout")
                && delegate.hook.as_deref() == Some("set_eq_layout"),
            "unsupported SDK config operation {}::{:?}",
            delegate.owner,
            delegate.property
        );
        ensure!(delegate.fields.len() == 1, "EQ layout requires one input");
        let input = &delegate.fields[0];
        ensure!(
            compact(&input.rust_type) == "Vec<EqBandConfig>",
            "unsupported EQ layout input {}",
            input.rust_type
        );
        let retained = registrations
            .iter()
            .find(|registration| {
                registration.kind == "retained"
                    && registration.package == "kithara-effects"
                    && registration.owner == "EqBandConfig"
            })
            .ok_or_else(|| anyhow::anyhow!("EqBandConfig is not registered"))?;
        render_record(&mut output, retained)?;
    }
    for retained in registrations
        .iter()
        .filter(|registration| registration.kind == "retained" && registration.sdk)
    {
        render_sdk_record(&mut output, retained)?;
    }
    render_queue_settings(&mut output, registrations)?;
    Ok(output)
}

pub(super) fn render_source(registrations: &[Registration]) -> Result<String> {
    let mut output =
        String::from("// @generated by `just tooling xtask config project`; do not edit.\n");
    render_source_settings(&mut output, registrations)?;
    Ok(output)
}

fn render_queue_settings(output: &mut String, registrations: &[Registration]) -> Result<()> {
    let Some(queue) = registrations.iter().find(|registration| {
        registration.package == "kithara-queue" && registration.owner == "QueueConfig"
    }) else {
        return Ok(());
    };
    let fields: Vec<_> = queue.fields.iter().filter(|field| field.sdk).collect();
    ensure!(!fields.is_empty(), "QueueConfig has no SDK fields");
    output.push_str("\n/// Optional queue settings applied before the player joins its host.\n");
    output.push_str("#[derive(Clone, Copy, Debug, Default, PartialEq)]\n");
    output.push_str("#[cfg_attr(\n    any(feature = \"uniffi\", feature = \"uniffi-web\"),\n    derive(uniffi::Record)\n)]\n");
    output.push_str("pub struct FfiQueueSettings {\n");
    for field in &fields {
        ensure!(
            field.role == "value" && !field.docs.is_empty(),
            "QueueConfig SDK field {} needs a documented value",
            field.name
        );
        for line in &field.docs {
            writeln!(output, "    /// {}", ffi_doc_line(line))?;
        }
        writeln!(
            output,
            "    pub {}: Option<{}>,",
            field.name,
            queue_wire_type(field)?
        )?;
    }
    output.push_str("}\n\nimpl FfiQueueSettings {\n");
    output.push_str("    pub(crate) fn validated_patch(\n        self,\n    ) -> Result<kithara::queue::QueueConfigPatch, crate::types::FfiError> {\n        let mut patch = kithara::queue::QueueConfigPatch::default();\n");
    for field in &fields {
        let name = &field.name;
        if name == "should_autoplay" {
            continue;
        }
        writeln!(output, "        if let Some(value) = self.{name} {{")?;
        match queue_value_type(field)?.as_str() {
            "NonZeroUsize" => {
                writeln!(
                    output,
                    "            patch.{name} =\n                Some(std::num::NonZeroUsize::new(value as usize).ok_or_else(|| {{\n                    crate::types::FfiError::InvalidArgument {{\n                        reason: \"{name} must be greater than zero\".into(),\n                    }}\n                }})?);"
                )?;
            }
            "usize" => writeln!(output, "            patch.{name} = Some(value as usize);")?,
            "f32" => {
                writeln!(
                    output,
                    "            if !value.is_finite() || value < 0.0 {{\n                return Err(crate::types::FfiError::InvalidArgument {{\n                    reason: \"{name} must be a finite nonnegative number\".into(),\n                }});\n            }}"
                )?;
                writeln!(output, "            patch.{name} = Some(value);")?;
            }
            "bool" => writeln!(output, "            patch.{name} = Some(value);")?,
            "PlaybackOrder" | "ActionAtItemEnd" | "CrossfadeSettings" => {
                writeln!(
                    output,
                    "            patch.{name} = Some(value.try_into()?);"
                )?;
            }
            other => bail!("unsupported QueueConfig SDK conversion {name}: {other}"),
        }
        output.push_str("        }\n");
    }
    output.push_str("        Ok(patch)\n    }\n\n    pub(crate) fn apply_to<S>(\n        self,\n        config: &mut kithara::queue::QueueConfig<S>,\n    ) -> Result<(), crate::types::FfiError>\n    where\n        S: kithara::bufpool::HasPool<u8> + kithara::bufpool::HasPool<f32> + Send + Sync + 'static,\n    {\n        let patch = self.validated_patch()?;\n        config.apply(patch);\n");
    if fields.iter().any(|field| field.name == "should_autoplay") {
        output.push_str("        if let Some(value) = self.should_autoplay {\n            config.should_autoplay = value;\n        }\n");
    }
    output.push_str("        Ok(())\n    }\n}\n");
    Ok(())
}

fn queue_value_type(field: &RegisteredField) -> Result<String> {
    field
        .value_type
        .as_deref()
        .map(compact)
        .ok_or_else(|| anyhow::anyhow!("QueueConfig SDK field {} has no value type", field.name))
}

fn queue_wire_type(field: &RegisteredField) -> Result<&'static str> {
    match queue_value_type(field)?.as_str() {
        "NonZeroUsize" | "usize" => Ok("u32"),
        "f32" => Ok("f32"),
        "bool" => Ok("bool"),
        "PlaybackOrder" => Ok("crate::types::FfiPlaybackOrder"),
        "ActionAtItemEnd" => Ok("crate::types::FfiActionAtItemEnd"),
        "CrossfadeSettings" => Ok("FfiCrossfadeSettings"),
        other => bail!("unsupported QueueConfig SDK field {}: {other}", field.name),
    }
}

pub(super) fn render_host(registrations: &[Registration]) -> Result<String> {
    let exposed: Vec<_> = registrations
        .iter()
        .filter(|registration| registration.kind == "construction" && registration.sdk)
        .collect();
    ensure!(
        exposed.len() == 1,
        "expected one SDK host construction config"
    );
    let mut output = String::from(
        "// @generated by `just tooling xtask config project`; do not edit.\n\
         use super::config_generated::FfiLimiterConfig;\n",
    );
    render_host_config(&mut output, exposed[0])?;
    Ok(output)
}

fn render_host_config(output: &mut String, registration: &Registration) -> Result<()> {
    ensure!(
        registration.package == "kithara-host" && registration.owner == "HostConfig::Realtime",
        "unsupported SDK construction config {}::{}",
        registration.package,
        registration.owner
    );
    output.push_str("\n/// Settings fixed for the lifetime of the process-wide audio host.\n");
    output.push_str("#[derive(Clone, Copy, Debug, PartialEq)]\n");
    output.push_str("#[cfg_attr(\n    any(feature = \"uniffi\", feature = \"uniffi-web\"),\n    derive(uniffi::Record)\n)]\n");
    output.push_str("#[cfg_attr(target_arch = \"wasm32\", wasm_bindgen::prelude::wasm_bindgen)]\n");
    output.push_str("pub struct FfiHostConfig {\n");
    for field in readable_fields(registration) {
        for line in &field.docs {
            writeln!(output, "    /// {}", ffi_doc_line(line))?;
        }
        let wire_type = match (field.role.as_str(), compact(&field.rust_type).as_str()) {
            ("value", "NonZeroU32") => "u32",
            ("value", "Option<NonZeroU32>") => "Option<u32>",
            ("nested", "LimiterConfig") => "FfiLimiterConfig",
            _ => bail!(
                "unsupported HostConfig SDK field {}: {}",
                field.name,
                field.rust_type
            ),
        };
        writeln!(output, "    pub {}: {wire_type},", field.name)?;
    }
    output.push_str("}\n\nimpl FfiHostConfig {\n");
    output.push_str("    pub(crate) fn into_domain<S>(\n        self,\n    ) -> Result<kithara::host::HostConfig<S>, crate::types::FfiError> {\n");
    for field in readable_fields(registration) {
        let name = &field.name;
        match compact(&field.rust_type).as_str() {
            "NonZeroU32" => {
                ensure!(
                    name == "sample_rate_hint",
                    "unsupported required HostConfig field {name}"
                );
                writeln!(output, "        let {name} =")?;
                writeln!(
                    output,
                    "            std::num::NonZeroU32::new(self.{name}).ok_or_else(|| {{"
                )?;
                output.push_str("                crate::types::FfiError::InvalidArgument {\n                    reason: \"host sample rate must be greater than zero\".to_owned(),\n                }\n            })?;\n");
            }
            "Option<NonZeroU32>" => {
                ensure!(
                    name == "output_block_frames",
                    "unsupported optional HostConfig field {name}"
                );
                writeln!(output, "        let {name} = self")?;
                writeln!(output, "            .{name}")?;
                output.push_str("            .map(|frames| {\n                std::num::NonZeroU32::new(frames).ok_or_else(|| {\n                    crate::types::FfiError::InvalidArgument {\n                        reason: \"host output block size must be greater than zero\".to_owned(),\n                    }\n                })\n            })\n            .transpose()?;\n");
            }
            "LimiterConfig" => {
                ensure!(
                    name == "limiter",
                    "unsupported nested HostConfig field {name}"
                );
                writeln!(output, "        let {name} = self.{name}.try_into()?;")?;
            }
            _ => bail!(
                "unsupported HostConfig SDK conversion {}: {}",
                name,
                field.rust_type
            ),
        }
    }
    output.push_str("        Ok(kithara::host::HostConfig::builder()\n");
    for field in readable_fields(registration) {
        if compact(&field.rust_type) == "Option<NonZeroU32>" {
            writeln!(output, "            .maybe_{}({})", field.name, field.name)?;
        } else {
            writeln!(output, "            .{}({})", field.name, field.name)?;
        }
    }
    output.push_str("            .build())\n    }\n}\n");
    Ok(())
}

fn render_source_settings(output: &mut String, registrations: &[Registration]) -> Result<()> {
    let exposed: Vec<_> = registrations
        .iter()
        .filter(|registration| {
            registration.kind == "construction" && registration.fields.iter().any(|field| field.sdk)
        })
        .collect();
    if exposed.is_empty() {
        return Ok(());
    }
    let owners = [
        ("kithara-file", "FileConfig", "File"),
        ("kithara-hls", "HlsConfig", "Hls"),
    ];
    if exposed.iter().any(|registration| {
        registration.package == "kithara-hls"
            && registration
                .fields
                .iter()
                .any(|field| field.sdk && field.name == "size_probe_method")
    }) {
        output.push_str(
            "\n/// HTTP method used to probe an HLS segment's exact size.\n\
             #[derive(Clone, Copy, Debug, PartialEq, Eq)]\n\
             #[cfg_attr(any(feature = \"uniffi\", feature = \"uniffi-web\"), derive(uniffi::Enum))]\n\
             pub enum FfiSizeProbeMethod {\n\
             \x20\x20\x20\x20/// Probe with HTTP HEAD.\n\
             \x20\x20\x20\x20Head,\n\
             \x20\x20\x20\x20/// Probe with a one-byte ranged GET.\n\
             \x20\x20\x20\x20RangeGet,\n\
             \x20\x20\x20\x20/// Reserved value rejected when configuring an item.\n\
             \x20\x20\x20\x20Unknown,\n\
             }\n\n\
             impl TryFrom<FfiSizeProbeMethod> for kithara_hls::SizeProbeMethod {\n\
             \x20\x20\x20\x20type Error = crate::types::FfiError;\n\n\
             \x20\x20\x20\x20fn try_from(value: FfiSizeProbeMethod) -> Result<Self, Self::Error> {\n\
             \x20\x20\x20\x20\x20\x20\x20\x20match value {\n\
             \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20FfiSizeProbeMethod::Head => Ok(Self::Head),\n\
             \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20FfiSizeProbeMethod::RangeGet => Ok(Self::RangeGet),\n\
             \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20FfiSizeProbeMethod::Unknown => Err(crate::types::FfiError::InvalidArgument {\n\
             \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20reason: \"unknown HLS size probe method\".into(),\n\
             \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20}),\n\
             \x20\x20\x20\x20\x20\x20\x20\x20}\n\
             \x20\x20\x20\x20}\n\
             }\n",
        );
    }
    for (package, owner, prefix) in owners {
        let registration = exposed
            .iter()
            .find(|registration| registration.package == package && registration.owner == owner)
            .ok_or_else(|| {
                anyhow::anyhow!("missing SDK source settings owner {package}::{owner}")
            })?;
        ensure!(
            registration.kind == "construction",
            "SDK source settings owner {package}::{owner} must be a construction input"
        );
        render_source_record(output, registration, prefix)?;
    }
    ensure!(
        exposed.len() == owners.len(),
        "unsupported SDK source settings owner"
    );
    output.push_str(
        r#"
/// Per-item source settings, applied before opening the file or HLS stream.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
#[cfg_attr(
    any(feature = "uniffi", feature = "uniffi-web"),
    derive(uniffi::Record)
)]
pub struct FfiSourceSettings {
    /// File-stream settings, when supplied.
    pub file: Option<FfiFileSourceSettings>,
    /// HLS-stream settings, when supplied.
    pub hls: Option<FfiHlsSourceSettings>,
}
"#,
    );
    Ok(())
}

fn render_source_record(
    output: &mut String,
    registration: &Registration,
    prefix: &str,
) -> Result<()> {
    let fields: Vec<_> = registration
        .fields
        .iter()
        .filter(|field| field.sdk)
        .collect();
    let record = format!("Ffi{prefix}SourceSettings");
    writeln!(
        output,
        "\n/// Optional {prefix} stream settings for one item."
    )?;
    output.push_str("#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]\n");
    output.push_str("#[cfg_attr(\n    any(feature = \"uniffi\", feature = \"uniffi-web\"),\n    derive(uniffi::Record)\n)]\n");
    writeln!(output, "pub struct {record} {{")?;
    for field in &fields {
        render_source_field(output, registration, field)?;
    }
    output.push_str("}\n");
    writeln!(
        output,
        "\nimpl TryFrom<{record}> for kithara_{}::{}Patch {{",
        if prefix == "File" { "file" } else { "hls" },
        registration.owner
    )?;
    output.push_str("    type Error = crate::types::FfiError;\n\n");
    writeln!(
        output,
        "    fn try_from(value: {record}) -> Result<Self, Self::Error> {{"
    )?;
    output.push_str("        let mut patch = Self::default();\n");
    for field in fields {
        writeln!(
            output,
            "        if let Some(input) = value.{} {{",
            field.name
        )?;
        match compact(&field.rust_type).as_str() {
            "u8" => {
                let maximum = field.sdk_max.unwrap_or_default();
                writeln!(output, "            if input > {maximum} {{")?;
                output.push_str(
                    "                return Err(crate::types::FfiError::InvalidArgument {\n",
                );
                writeln!(
                    output,
                    "                    reason: \"{}.{} must be in 0..={maximum}\".into(),",
                    registration.owner, field.name
                )?;
                output.push_str("                });\n            }\n");
                writeln!(
                    output,
                    "            patch.{} =\n                Some(\n                    u8::try_from(input).map_err(|_| crate::types::FfiError::InvalidArgument {{",
                    field.name
                )?;
                writeln!(
                    output,
                    "                        reason: \"{}.{} exceeds u8\".into(),",
                    registration.owner, field.name
                )?;
                output.push_str("                    })?,\n                );\n");
            }
            "usize" => {
                let maximum = field.sdk_max.unwrap_or_default();
                writeln!(output, "            if input == 0 || input > {maximum} {{")?;
                output.push_str(
                    "                return Err(crate::types::FfiError::InvalidArgument {\n",
                );
                writeln!(
                    output,
                    "                    reason: \"{}.{} must be in 1..={maximum}\".into(),",
                    registration.owner, field.name
                )?;
                output.push_str("                });\n            }\n");
                writeln!(
                    output,
                    "            patch.{} = Some(input as usize);",
                    field.name
                )?;
            }
            "SizeProbeMethod" => writeln!(
                output,
                "            patch.{} = Some(input.try_into()?);",
                field.name
            )?,
            "Option<u64>" => {
                let maximum = field.sdk_max.unwrap_or_default();
                writeln!(output, "            if input > {maximum} {{")?;
                output.push_str(
                    "                return Err(crate::types::FfiError::InvalidArgument {\n",
                );
                writeln!(
                    output,
                    "                    reason: \"{}.{} must be in 0..={maximum}\".into(),",
                    registration.owner, field.name
                )?;
                output.push_str("                });\n            }\n");
                writeln!(
                    output,
                    "            patch.{} = Some(Some(input));",
                    field.name
                )?;
            }
            _ => unreachable!("field type was checked while rendering the record"),
        }
        output.push_str("        }\n");
    }
    output.push_str("        Ok(patch)\n    }\n}\n");
    Ok(())
}

fn render_source_field(
    output: &mut String,
    registration: &Registration,
    field: &RegisteredField,
) -> Result<()> {
    ensure!(
        field.role == "value" && !field.docs.is_empty(),
        "SDK source field {}.{} needs a documented value",
        registration.owner,
        field.name
    );
    for line in &field.docs {
        writeln!(output, "    /// {}", ffi_doc_line(line))?;
    }
    let kind = compact(&field.rust_type);
    match kind.as_str() {
        "u8" | "usize" => {
            let maximum = field.sdk_max.ok_or_else(|| {
                anyhow::anyhow!(
                    "SDK source field {}.{} needs a maximum",
                    registration.owner,
                    field.name
                )
            })?;
            if kind == "u8" {
                ensure!(
                    maximum <= u32::from(u8::MAX),
                    "SDK source u8 maximum exceeds 255"
                );
            }
            let minimum = if kind == "u8" { 0 } else { 1 };
            writeln!(output, "    /// Accepted range: {minimum}..={maximum}.")?;
            writeln!(output, "    pub {}: Option<u32>,", field.name)?;
        }
        "SizeProbeMethod" if registration.package == "kithara-hls" => {
            ensure!(
                field.sdk_max.is_none(),
                "size probe method has no numeric maximum"
            );
            writeln!(
                output,
                "    pub {}: Option<FfiSizeProbeMethod>,",
                field.name
            )?;
        }
        "Option<u64>" => {
            let maximum = field.sdk_max.ok_or_else(|| {
                anyhow::anyhow!(
                    "SDK source field {}.{} needs a maximum",
                    registration.owner,
                    field.name
                )
            })?;
            writeln!(output, "    /// Accepted range: 0..={maximum} bytes.")?;
            writeln!(output, "    pub {}: Option<u64>,", field.name)?;
        }
        _ => bail!(
            "unsupported SDK source field {}.{}: {}",
            registration.owner,
            field.name,
            field.rust_type
        ),
    }
    Ok(())
}

fn render_sdk_record(output: &mut String, registration: &Registration) -> Result<()> {
    ensure!(
        registration
            .fields
            .iter()
            .all(|field| field.role == "value"),
        "SDK value projection requires value fields: {}",
        registration.owner
    );
    let fields: Vec<_> = readable_fields(registration).collect();
    ensure!(
        !fields.is_empty(),
        "empty SDK config: {}",
        registration.owner
    );
    if registration.owner == "CrossfadeSettings" {
        ensure!(
            registration.package == "kithara-play"
                && fields
                    .iter()
                    .map(|field| field.name.as_str())
                    .collect::<Vec<_>>()
                    == ["duration", "curve", "depth", "position"]
                && fields
                    .iter()
                    .map(|field| compact(&field.rust_type))
                    .collect::<Vec<_>>()
                    == ["f32", "CrossfadeCurve", "f32", "f32"],
            "CrossfadeSettings SDK conversion requires duration: f32, curve: CrossfadeCurve, depth: f32, position: f32"
        );
    }
    output.push('\n');
    for line in &registration.docs {
        writeln!(output, "/// {}", ffi_doc_line(line))?;
    }
    output.push_str("#[derive(Clone, Copy, Debug, PartialEq)]\n");
    output.push_str(
        "#[cfg_attr(\n    any(feature = \"uniffi\", feature = \"uniffi-web\"),\n    derive(uniffi::Record)\n)]\n",
    );
    if registration.owner != "CrossfadeSettings" {
        output.push_str(
            "#[cfg_attr(target_arch = \"wasm32\", wasm_bindgen::prelude::wasm_bindgen)]\n",
        );
    }
    writeln!(output, "pub struct Ffi{} {{", registration.owner)?;
    for field in &fields {
        for line in &field.docs {
            writeln!(output, "    /// {}", ffi_doc_line(line))?;
        }
        let wire_type = ffi_type(field)?;
        ensure!(
            matches!(wire_type, "f32" | "u32" | "i32" | "bool")
                || registration.owner == "CrossfadeSettings"
                    && wire_type == "crate::types::FfiCrossfadeCurve",
            "SDK config field {}.{} needs a scalar Web mapping",
            registration.owner,
            field.name
        );
        writeln!(output, "    pub {}: {wire_type},", field.name)?;
    }
    output.push_str("}\n");
    if registration.owner == "CrossfadeSettings" {
        output.push_str("\nimpl Default for FfiCrossfadeSettings {\n    fn default() -> Self {\n        kithara::play::CrossfadeSettings::default().into()\n    }\n}\n");
        output.push_str("\nimpl From<kithara::play::CrossfadeSettings> for FfiCrossfadeSettings {\n    fn from(value: kithara::play::CrossfadeSettings) -> Self {\n        let values = kithara_config::Config::values(&value);\n        Self {\n            duration: values.duration,\n            curve: match values.curve {\n                kithara::play::CrossfadeCurve::Linear => crate::types::FfiCrossfadeCurve::Linear,\n                kithara::play::CrossfadeCurve::EqualPower => {\n                    crate::types::FfiCrossfadeCurve::EqualPower\n                }\n                _ => crate::types::FfiCrossfadeCurve::Unknown,\n            },\n            depth: values.depth,\n            position: values.position,\n        }\n    }\n}\n\nimpl TryFrom<FfiCrossfadeSettings> for kithara::play::CrossfadeSettings {\n    type Error = crate::types::FfiError;\n\n    fn try_from(value: FfiCrossfadeSettings) -> Result<Self, Self::Error> {\n        let curve = match value.curve {\n            crate::types::FfiCrossfadeCurve::Linear => kithara::play::CrossfadeCurve::Linear,\n            crate::types::FfiCrossfadeCurve::EqualPower => {\n                kithara::play::CrossfadeCurve::EqualPower\n            }\n            crate::types::FfiCrossfadeCurve::Unknown => {\n                return Err(crate::types::FfiError::InvalidArgument {\n                    reason: \"unknown crossfade curve\".into(),\n                });\n            }\n        };\n        Self::new(value.duration, curve, value.depth, value.position)\n            .map_err(crate::types::FfiError::from)\n    }\n}\n");
    }
    if registration.package == "kithara-effects" && registration.owner == "LimiterConfig" {
        output.push_str("\nimpl Default for FfiLimiterConfig {\n    fn default() -> Self {\n        let config = kithara::effects::LimiterConfig::default();\n        Self {\n");
        for field in &fields {
            writeln!(
                output,
                "            {}: config.{}(),",
                field.name, field.name
            )?;
        }
        output.push_str("        }\n    }\n}\n\nimpl TryFrom<FfiLimiterConfig> for kithara::effects::LimiterConfig {\n    type Error = crate::types::FfiError;\n\n    fn try_from(config: FfiLimiterConfig) -> Result<Self, Self::Error> {\n        Self::builder()\n");
        for field in &fields {
            writeln!(output, "            .{}(config.{})", field.name, field.name)?;
        }
        output.push_str("            .build()\n            .map_err(|error| crate::types::FfiError::InvalidArgument {\n                reason: error.to_string(),\n            })\n    }\n}\n");
    }
    Ok(())
}

fn ffi_doc_line(line: &str) -> String {
    line.replace("[`", "`").replace("`]", "`")
}

fn render_record(output: &mut String, registration: &Registration) -> Result<()> {
    for line in &registration.docs {
        writeln!(output, "/// {line}")?;
    }
    output.push_str(
        "#[derive(Clone, Debug, PartialEq)]\n\
         #[cfg_attr(\n    any(feature = \"uniffi\", feature = \"uniffi-web\"),\n    derive(uniffi::Record)\n)]\n\
         pub struct FfiEqBandConfig {\n",
    );
    for field in readable_fields(registration) {
        for line in &field.docs {
            writeln!(output, "    /// {line}")?;
        }
        writeln!(output, "    pub {}: {},", field.name, ffi_type(field)?)?;
    }
    output.push_str("}\n\nimpl From<FfiEqBandConfig> for EqBandConfig {\n    fn from(value: FfiEqBandConfig) -> Self {\n        Self::builder()\n");
    for field in readable_fields(registration) {
        writeln!(
            output,
            "            .{}({})",
            field.name,
            into_domain(field, &format!("value.{}", field.name))?
        )?;
    }
    output.push_str("            .build()\n    }\n}\n");
    Ok(())
}

fn readable_fields(registration: &Registration) -> impl Iterator<Item = &RegisteredField> {
    registration
        .fields
        .iter()
        .filter(|field| field.role != "skip")
}

fn ffi_type(field: &RegisteredField) -> Result<&'static str> {
    match compact(&field.rust_type).as_str() {
        "FilterKind" => Ok("FfiEqFilterKind"),
        "GainDb" | "f32" => Ok("f32"),
        "CrossfadeCurve" => Ok("crate::types::FfiCrossfadeCurve"),
        other => bail!("no FFI type mapping for {other}"),
    }
}

fn into_domain(field: &RegisteredField, value: &str) -> Result<String> {
    Ok(match compact(&field.rust_type).as_str() {
        "FilterKind" => format!(
            "match {value} {{\n                FfiEqFilterKind::LowShelf => FilterKind::LowShelf,\n                FfiEqFilterKind::Peaking => FilterKind::Peaking,\n                FfiEqFilterKind::HighShelf => FilterKind::HighShelf,\n            }}"
        ),
        "GainDb" => format!("GainDb::from({value})"),
        "f32" => value.to_owned(),
        other => bail!("no domain conversion for {other}"),
    })
}

fn compact(value: &str) -> String {
    value
        .chars()
        .filter(|character| !character.is_whitespace())
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config_inventory::discover::registrations;

    #[test]
    fn queue_settings_follow_owner_fields_and_reject_unmapped_types() {
        let source = include_str!("../../../crates/kithara-queue/src/config.rs");
        let registered = registrations("crates/kithara-queue/src/config.rs", source).unwrap();
        let mut generated = String::new();
        render_queue_settings(&mut generated, &registered).unwrap();
        assert!(generated.contains("pub struct FfiQueueSettings"));
        assert!(generated.contains("pub max_concurrent_loads: Option<u32>"));
        assert!(
            generated.contains("pub action_at_item_end: Option<crate::types::FfiActionAtItemEnd>")
        );
        assert!(generated.contains("config.should_autoplay = value"));
        assert!(generated.contains("config.apply(patch)"));

        let unsupported = source.replace(
            "pub max_history_size: usize,",
            "pub max_history_size: Mystery,",
        );
        let registered = registrations("crates/kithara-queue/src/config.rs", &unsupported).unwrap();
        assert!(
            render_queue_settings(&mut String::new(), &registered)
                .unwrap_err()
                .to_string()
                .contains("Mystery")
        );
    }

    #[test]
    fn host_record_follows_realtime_registration_and_rejects_unknown_fields() {
        let host = r#"
            #[kithara_config::config(construction, builder = false)]
            enum HostConfig<S> {
                #[config(sdk)]
                Realtime {
                    /// Initial device rate.
                    #[config(value)] sample_rate_hint: NonZeroU32,
                    /// Optional callback block size.
                    #[config(value)] output_block_frames: Option<NonZeroU32>,
                    /// Limiter policy.
                    #[config(nested)] limiter: LimiterConfig,
                    #[config(skip = "type marker")] marker: PhantomData<S>,
                }
            }
        "#;
        let limiter = r#"
            #[kithara_config::config(builder = false, sdk)]
            struct LimiterConfig {
                #[config(value)] ceiling: f32,
                #[config(value)] release_ms: f32,
            }
            #[kithara_config::config]
            struct EqBandConfig {
                #[config(value)] frequency: f32,
            }
        "#;
        let delegate = r#"
            impl PlayerControl {
                #[kithara_config::config(delegate = "eq_layout", sdk)]
                fn set_eq_layout(&self, layout: Vec<EqBandConfig>) {}
            }
        "#;
        let mut registered = registrations("crates/kithara-host/src/host/config.rs", host).unwrap();
        registered.extend(registrations("crates/kithara-effects/src/eq.rs", limiter).unwrap());
        registered.extend(registrations("crates/kithara-play/src/player.rs", delegate).unwrap());
        let generated = render_host(&registered).unwrap();
        assert!(generated.contains("pub struct FfiHostConfig"));
        assert!(generated.contains("pub output_block_frames: Option<u32>"));
        assert!(generated.contains(".maybe_output_block_frames(output_block_frames)"));
        assert!(generated.contains("/// Initial device rate."));

        let unsupported = host.replace(
            "#[config(nested)] limiter: LimiterConfig,",
            "#[config(nested)] limiter: LimiterConfig, #[config(value)] mystery: String,",
        );
        let mut registered =
            registrations("crates/kithara-host/src/host/config.rs", &unsupported).unwrap();
        registered.extend(registrations("crates/kithara-effects/src/eq.rs", limiter).unwrap());
        registered.extend(registrations("crates/kithara-play/src/player.rs", delegate).unwrap());
        assert!(
            render_host(&registered)
                .unwrap_err()
                .to_string()
                .contains("mystery")
        );
    }

    #[test]
    fn projection_follows_registered_fields_and_rejects_unknown_types() {
        let source = r#"
            #[kithara_config::config]
            struct EqBandConfig {
                /// Frequency in hertz.
                #[config(value)] frequency: f32,
            }
        "#;
        let delegate = r#"
            impl PlayerControl {
                #[kithara_config::config(delegate = "eq_layout", sdk)]
                fn set_eq_layout(&self, layout: Vec<EqBandConfig>) {}
            }
        "#;
        let mut registered =
            registrations("crates/kithara-effects/src/eq/band.rs", source).unwrap();
        registered.extend(registrations("crates/kithara-play/src/player.rs", delegate).unwrap());
        let generated = render(&registered).unwrap();
        assert!(generated.contains("pub frequency: f32"));
        assert!(generated.contains(".frequency(value.frequency)"));

        let unsupported = source.replace("frequency: f32", "frequency: Mystery");
        let mut registered =
            registrations("crates/kithara-effects/src/eq/band.rs", &unsupported).unwrap();
        registered.extend(registrations("crates/kithara-play/src/player.rs", delegate).unwrap());
        assert!(
            render(&registered)
                .unwrap_err()
                .to_string()
                .contains("Mystery")
        );
    }

    #[test]
    fn opted_in_sdk_record_uses_registered_scalar_fields() {
        let source = r#"
            /// Limiter settings.
            #[kithara_config::config(builder = false, sdk)]
            struct LimiterConfig {
                /// Output ceiling.
                #[config(value)] ceiling: f32,
                /// Release in milliseconds.
                #[config(value)] release_ms: f32,
            }
            #[kithara_config::config]
            struct EqBandConfig {
                #[config(value)] frequency: f32,
            }
        "#;
        let delegate = r#"
            impl PlayerControl {
                #[kithara_config::config(delegate = "eq_layout", sdk)]
                fn set_eq_layout(&self, layout: Vec<EqBandConfig>) {}
            }
        "#;
        let mut registered = registrations("crates/kithara-effects/src/eq.rs", source).unwrap();
        registered.extend(registrations("crates/kithara-play/src/player.rs", delegate).unwrap());
        let generated = render(&registered).unwrap();
        assert!(generated.contains("pub struct FfiLimiterConfig"));
        assert!(generated.contains("pub release_ms: f32"));
        assert!(generated.contains("/// Release in milliseconds."));
        assert!(generated.contains("release_ms: config.release_ms()"));
        assert!(generated.contains(".release_ms(config.release_ms)"));

        let unsupported = source.replace("ceiling: f32", "ceiling: FilterKind");
        let mut registered =
            registrations("crates/kithara-effects/src/eq.rs", &unsupported).unwrap();
        registered.extend(registrations("crates/kithara-play/src/player.rs", delegate).unwrap());
        assert!(
            render(&registered)
                .unwrap_err()
                .to_string()
                .contains("scalar Web mapping")
        );
    }

    #[test]
    fn crossfade_projection_rejects_unmapped_fields() {
        let source = r#"
            #[kithara_config::config(builder = false, sdk)]
            struct CrossfadeSettings {
                #[config(value)] duration: f32,
                #[config(value)] curve: CrossfadeCurve,
                #[config(value)] depth: f32,
                #[config(value)] position: f32,
            }
            impl PlayerControl {
                #[kithara_config::config(delegate = "eq_layout", sdk)]
                fn set_eq_layout(&self, layout: Vec<EqBandConfig>) {}
            }
        "#;
        let band =
            "#[kithara_config::config] struct EqBandConfig { #[config(value)] frequency: f32 }";
        let mut registered =
            registrations("crates/kithara-play/src/api/crossfade.rs", source).unwrap();
        registered.extend(registrations("crates/kithara-effects/src/eq/band.rs", band).unwrap());
        let generated = render(&registered).unwrap();
        assert!(generated.contains("let values = kithara_config::Config::values(&value)"));
        assert!(
            generated.contains("Self::new(value.duration, curve, value.depth, value.position)")
        );

        let extra = source.replace(
            "#[config(value)] position: f32,",
            "#[config(value)] position: f32, #[config(value)] offset: f32,",
        );
        let mut registered =
            registrations("crates/kithara-play/src/api/crossfade.rs", &extra).unwrap();
        registered.extend(registrations("crates/kithara-effects/src/eq/band.rs", band).unwrap());
        assert!(
            render(&registered)
                .unwrap_err()
                .to_string()
                .contains("CrossfadeSettings SDK conversion requires")
        );
    }

    #[test]
    fn source_projection_follows_owner_fields_and_limits() {
        let mut registered = registrations(
            "crates/kithara-effects/src/eq/band.rs",
            "#[kithara_config::config] struct EqBandConfig { #[config(value)] frequency: f32 }",
        )
        .unwrap();
        registered.extend(
            registrations(
                "crates/kithara-play/src/player.rs",
                "impl PlayerControl { #[kithara_config::config(delegate = \"eq_layout\", sdk)] fn set_eq_layout(&self, layout: Vec<EqBandConfig>) {} }",
            )
            .unwrap(),
        );
        for (path, owner, field, max) in [
            (
                "crates/kithara-file/src/config.rs",
                "FileConfig",
                "reader_event_capacity",
                4096,
            ),
            (
                "crates/kithara-hls/src/config.rs",
                "HlsConfig",
                "download_batch_size",
                64,
            ),
        ] {
            let probe = if owner == "HlsConfig" {
                " /// Acquire attempts.\n #[config(value, sdk(max = 255))] acquire_attempt_budget: u8, \
                 /// Probe method.\n #[config(value, sdk)] size_probe_method: SizeProbeMethod, \
                 /// Look-ahead limit.\n #[config(value, sdk(max = 8388608))] look_ahead_bytes: Option<u64>"
            } else {
                " /// Look-ahead limit.\n #[config(value, sdk(max = 8388608))] look_ahead_bytes: Option<u64>"
            };
            registered.extend(
                registrations(
                    path,
                    &format!(
                        "#[kithara_config::config(construction)] struct {owner} {{ /// Capacity.\n #[config(value, sdk(max = {max}))] {field}: usize, {probe} }}"
                    ),
                )
                .unwrap(),
            );
        }
        let generated = render_source(&registered).unwrap();
        assert!(generated.contains("pub reader_event_capacity: Option<u32>"));
        assert!(generated.contains("patch.look_ahead_bytes = Some(Some(input))"));
        assert!(generated.contains("pub download_batch_size: Option<u32>"));
        assert!(generated.contains("pub acquire_attempt_budget: Option<u32>"));
        assert!(generated.contains("patch.acquire_attempt_budget ="));
        assert!(generated.contains("u8::try_from(input)"));
        assert!(generated.contains("pub size_probe_method: Option<FfiSizeProbeMethod>"));
        assert!(generated.contains("pub look_ahead_bytes: Option<u64>"));
        assert!(generated.contains("patch.look_ahead_bytes = Some(Some(input))"));
        assert!(generated.contains("if input > 8388608"));
        assert!(generated.contains("patch.size_probe_method = Some(input.try_into()?)"));
        assert!(generated.contains("FfiSizeProbeMethod::Unknown => Err"));
        assert!(generated.contains("input > 4096"));
        assert!(generated.contains("input > 64"));
        assert!(generated.contains("patch.reader_event_capacity = Some(input as usize)"));
        assert!(generated.contains("patch.download_batch_size = Some(input as usize)"));

        let unsupported = registered
            .iter_mut()
            .find(|registration| registration.owner == "FileConfig")
            .unwrap();
        unsupported.fields[0].rust_type = "String".into();
        assert!(render_source(&registered).is_err());
    }
}
