use std::{fmt::Write as _, path::Path};

use anyhow::{Context, Result};
use tracing::info;

use super::{
    container::{Container, container},
    profile::LinuxHost,
    services::cpuset,
};
use crate::ci::config::CiPins;

/// Write the whole fleet as one Compose project, generated from the profile.
///
/// systemd stays the supervisor. A runner takes one job and exits, and the
/// registration it came up with is accepted once — so a Compose `restart:`
/// policy would bring it back holding a credential that is already spent. What
/// Compose is for here is the fleet as a unit: bring all of it up, read its
/// state, take it down, and grow it by editing the profile and generating
/// again. Both this file and the units come from `linux-host.toml`, so there is
/// still one description of the machine rather than two.
pub(super) fn write(host: &LinuxHost, pins: &CiPins, out: &Path) -> Result<()> {
    let cores = std::thread::available_parallelism()
        .context("reading this machine's core count")?
        .get();
    let project = project(host, pins, cores)?;
    std::fs::write(out, project).with_context(|| format!("writing {}", out.display()))?;
    info!(
        path = %out.display(),
        runners = host.runners.len(),
        "compose project written"
    );
    Ok(())
}

fn project(host: &LinuxHost, pins: &CiPins, cores: usize) -> Result<String> {
    let mut yaml = String::new();
    writeln!(
        yaml,
        "# Generated by `kithara-ci ci linux compose` from the machine profile.\n\
         # Edit the profile and generate again; edits here are lost.\n\
         #\n\
         # Every service needs its registration minted first, which is a host\n\
         # step because the token that mints it never enters a container:\n\
         #\n\
         #   kithara-ci ci linux compose --mint\n\
         #   docker compose -f {file} up -d\n\
         #\n\
         # No restart policy: a runner serves one job and exits, and the\n\
         # registration it holds is accepted once. Recycling is systemd's job.\n\
         name: kithara-ci\n\n\
         networks:\n  \
         default:\n    \
         name: {network}\n    \
         external: true\n\n\
         volumes:",
        file = FILE,
        network = host.network,
    )?;
    let mut volumes: Vec<String> = host
        .runners
        .iter()
        .flat_map(|runner| {
            Container::mounts(host, runner)
                .into_iter()
                .map(|(name, _)| name)
        })
        .filter(|name| Container::mount_type(name) == "volume")
        .collect();
    volumes.dedup();
    volumes.sort();
    volumes.dedup();
    for volume in &volumes {
        writeln!(yaml, "  {volume}:\n    external: true")?;
    }
    writeln!(yaml, "\nservices:")?;

    for (index, runner) in host.runners.iter().enumerate() {
        let unit = container(host, runner, cpuset(index, runner.cpus, cores), pins);
        writeln!(
            yaml,
            "  {name}:\n    \
             image: {image}\n    \
             container_name: {container}\n    \
             restart: \"no\"\n    \
             cpuset: \"{cpuset}\"\n    \
             mem_limit: {memory}\n    \
             pids_limit: {pids}\n    \
             security_opt: [\"no-new-privileges\"]\n    \
             env_file: [\"{env_file}\"]",
            name = runner.name,
            image = unit.image,
            container = unit.name,
            cpuset = unit.cpuset,
            memory = unit.memory,
            pids = Container::PIDS_LIMIT,
            env_file = unit.env_file,
        )?;
        writeln!(yaml, "    environment:")?;
        for entry in Container::environment() {
            writeln!(yaml, "      - {entry}")?;
        }
        writeln!(yaml, "    volumes:")?;
        for (volume, target) in &unit.mounts {
            writeln!(yaml, "      - {volume}:{target}")?;
        }
        if !unit.devices.is_empty() {
            writeln!(yaml, "    devices:")?;
            for device in unit.devices {
                let device = device.display();
                writeln!(yaml, "      - {device}:{device}")?;
            }
        }
        if !unit.groups.is_empty() {
            writeln!(yaml, "    group_add:")?;
            for group in unit.groups {
                writeln!(yaml, "      - \"{group}\"")?;
            }
        }
        yaml.push('\n');
    }
    Ok(yaml)
}

/// Where the generated project is written when no path is given.
pub(super) const FILE: &str = "/etc/kithara-ci/docker-compose.yml";

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ci::{config::fixture, linux::profile::tests::host_fixture};

    /// The fleet is generated, not written by hand: every runner in the profile
    /// gets a service, and none of them carries a restart policy that would
    /// bring it back holding a registration it already spent.
    #[test]
    fn every_runner_in_the_profile_becomes_a_service() {
        let host = host_fixture();
        let yaml = project(&host, &fixture().pins, 32).expect("the project must render");

        for runner in &host.runners {
            assert!(
                yaml.contains(&format!("  {}:\n", runner.name)),
                "runner {} has no service:\n{yaml}",
                runner.name
            );
        }
        assert_eq!(
            yaml.matches("restart: \"no\"").count(),
            host.runners.len(),
            "every service must decline to restart:\n{yaml}"
        );
    }

    /// The compiler cache was in the image and reaching nothing. Whichever way
    /// a runner is started, it must be told to use it — otherwise every job
    /// compiles the workspace from source and the only thing the machine shares
    /// is a build directory that cannot be shared.
    #[test]
    fn a_runner_is_told_to_use_the_compiler_cache() {
        let yaml = project(&host_fixture(), &fixture().pins, 32).expect("the project must render");
        for entry in Container::environment() {
            assert!(
                yaml.contains(&format!("      - {entry}")),
                "{entry}:\n{yaml}"
            );
        }
        assert!(yaml.contains("kithara-ci-sccache:/cache/sccache"), "{yaml}");
        assert!(
            yaml.contains("/var/lib/kithara-ci/shared-target:/cache/shared-target"),
            "{yaml}"
        );
        assert!(
            yaml.contains("/var/lib/kithara-ci/target/kithara-ci-octocat:/cache/target"),
            "{yaml}"
        );
    }

    /// The Android runner reaches hardware a plain one must not, and Compose
    /// has to carry that as faithfully as the unit does.
    #[test]
    fn a_runner_that_needs_a_device_is_given_it() {
        let host = host_fixture();
        let yaml = project(&host, &fixture().pins, 32).expect("the project must render");
        assert!(
            yaml.contains("      - /dev/kvm:/dev/kvm"),
            "the emulator runner must reach /dev/kvm:\n{yaml}"
        );
        assert!(
            yaml.contains("      - \"994\""),
            "it must join the group that owns the device:\n{yaml}"
        );
    }
}
