#!/usr/bin/env swift
// Bake DRM secrets into `Sources/Generated/Secrets.swift` at build time.
//
// Sources (in order of precedence):
//   1. Process env (`KITHARA_DRM_*`) — what Xcode passes down.
//   2. `$SRCROOT/.env` (kithara-style KEY=value lines, gitignored).
//
// Each secret is XOR'd with a per-build random pad of equal length
// and emitted as two `[UInt8]` literals. Neither literal contains the
// plain bytes, so `strings KitharaDemo` does not yield the cipher key
// or auth tokens. Runtime reveal lives in `Sources/Obfstr.swift`.
//
// The script is idempotent across builds — the pad is regenerated on
// every invocation, so the .o changes whenever the script runs, but
// the resulting binary still resolves to the same secret at runtime.

import Foundation

// MARK: - Inputs

let env = ProcessInfo.processInfo.environment

func dotenvPath() -> String? {
    if let srcroot = env["SRCROOT"] {
        let candidate = "\(srcroot)/.env"
        if FileManager.default.fileExists(atPath: candidate) { return candidate }
    }
    let cwd = FileManager.default.currentDirectoryPath
    let cwdCandidate = "\(cwd)/.env"
    if FileManager.default.fileExists(atPath: cwdCandidate) { return cwdCandidate }
    return nil
}

func loadDotenv() -> [String: String] {
    guard let path = dotenvPath(),
          let contents = try? String(contentsOfFile: path, encoding: .utf8)
    else { return [:] }

    var out: [String: String] = [:]
    for raw in contents.components(separatedBy: .newlines) {
        let line = raw.trimmingCharacters(in: .whitespaces)
        if line.isEmpty || line.hasPrefix("#") { continue }
        guard let eq = line.firstIndex(of: "=") else { continue }
        let key = line[..<eq].trimmingCharacters(in: .whitespaces)
        var value = String(line[line.index(after: eq)...]).trimmingCharacters(in: .whitespaces)
        if value.hasPrefix("\"") && value.hasSuffix("\"") || value.hasPrefix("'") && value.hasSuffix("'") {
            value = String(value.dropFirst().dropLast())
        }
        out[key] = value
    }
    return out
}

let dotenv = loadDotenv()

func lookup(_ key: String) -> String? {
    if let v = env[key], !v.isEmpty { return v }
    if let v = dotenv[key], !v.isEmpty { return v }
    return nil
}

// MARK: - Secrets we bake

struct SecretSlot {
    let swiftName: String
    let envKey: String
}

let slots: [SecretSlot] = [
    .init(swiftName: "prodCipherKey",  envKey: "KITHARA_DRM_PROD_KEY"),
    .init(swiftName: "prodAuthToken",  envKey: "KITHARA_DRM_PROD_AUTH_TOKEN"),
    .init(swiftName: "prodSpZvToken",  envKey: "KITHARA_DRM_PROD_SP_ZV_TOKEN"),
    .init(swiftName: "stageCipherKey", envKey: "KITHARA_DRM_STAGE_KEY"),
    .init(swiftName: "stageAuthToken", envKey: "KITHARA_DRM_STAGE_AUTH_TOKEN"),
]

// MARK: - XOR obfuscation

func obfuscate(_ value: String) -> (obf: [UInt8], pad: [UInt8]) {
    let bytes = Array(value.utf8)
    var pad = [UInt8](repeating: 0, count: bytes.count)
    let status = SecRandomCopyBytes(kSecRandomDefault, pad.count, &pad)
    precondition(status == errSecSuccess, "SecRandomCopyBytes failed")
    let obf = zip(bytes, pad).map { $0 ^ $1 }
    return (obf, pad)
}

func formatArray(_ bytes: [UInt8]) -> String {
    "[" + bytes.map { String(format: "0x%02x", $0) }.joined(separator: ", ") + "]"
}

// MARK: - Emit

var lines: [String] = [
    "// AUTO-GENERATED by scripts/bake-secrets.swift — do not edit.",
    "// Plain values never appear in this file or the compiled binary;",
    "// see `Obfstr.reveal(_:_:)` for the runtime de-obfuscation step.",
    "",
    "enum GeneratedSecrets {",
]

for slot in slots {
    let raw = lookup(slot.envKey) ?? ""
    if raw.isEmpty {
        FileHandle.standardError.write(Data(
            "[bake-secrets] warning: \(slot.envKey) is empty — \(slot.swiftName) will be \"\"\n".utf8
        ))
    }
    let (obf, pad) = obfuscate(raw)
    lines.append("    static let \(slot.swiftName)Obf: [UInt8] = \(formatArray(obf))")
    lines.append("    static let \(slot.swiftName)Pad: [UInt8] = \(formatArray(pad))")
    lines.append("    static var \(slot.swiftName): String {")
    lines.append("        Obfstr.reveal(\(slot.swiftName)Obf, \(slot.swiftName)Pad)")
    lines.append("    }")
    lines.append("")
}

lines.append("}")
lines.append("")

let outDir: String = {
    if let srcroot = env["SRCROOT"] { return "\(srcroot)/Sources/Generated" }
    return "\(FileManager.default.currentDirectoryPath)/Sources/Generated"
}()
try? FileManager.default.createDirectory(atPath: outDir, withIntermediateDirectories: true)

let outPath = "\(outDir)/Secrets.swift"
let text = lines.joined(separator: "\n")
try text.write(toFile: outPath, atomically: true, encoding: .utf8)

FileHandle.standardError.write(Data("[bake-secrets] wrote \(outPath) (\(slots.count) slots)\n".utf8))
